/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.jobs.requests;

import com.berrycrawl.core.ObjectMappers;
import com.berrycrawl.resources.jobs.types.ListJobsRequestStatus;
import com.berrycrawl.resources.jobs.types.ListJobsRequestType;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListJobsRequest.Builder.class
)
public final class ListJobsRequest {
  private final Optional<ListJobsRequestType> type;

  private final Optional<ListJobsRequestStatus> status;

  private final Optional<Double> page;

  private final Optional<Double> limit;

  private final Map<String, Object> additionalProperties;

  private ListJobsRequest(Optional<ListJobsRequestType> type,
      Optional<ListJobsRequestStatus> status, Optional<Double> page, Optional<Double> limit,
      Map<String, Object> additionalProperties) {
    this.type = type;
    this.status = status;
    this.page = page;
    this.limit = limit;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("type")
  public Optional<ListJobsRequestType> getType() {
    return type;
  }

  @JsonProperty("status")
  public Optional<ListJobsRequestStatus> getStatus() {
    return status;
  }

  @JsonProperty("page")
  public Optional<Double> getPage() {
    return page;
  }

  @JsonProperty("limit")
  public Optional<Double> getLimit() {
    return limit;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListJobsRequest && equalTo((ListJobsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListJobsRequest other) {
    return type.equals(other.type) && status.equals(other.status) && page.equals(other.page) && limit.equals(other.limit);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.type, this.status, this.page, this.limit);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<ListJobsRequestType> type = Optional.empty();

    private Optional<ListJobsRequestStatus> status = Optional.empty();

    private Optional<Double> page = Optional.empty();

    private Optional<Double> limit = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ListJobsRequest other) {
      type(other.getType());
      status(other.getStatus());
      page(other.getPage());
      limit(other.getLimit());
      return this;
    }

    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<ListJobsRequestType> type) {
      this.type = type;
      return this;
    }

    public Builder type(ListJobsRequestType type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    @JsonSetter(
        value = "status",
        nulls = Nulls.SKIP
    )
    public Builder status(Optional<ListJobsRequestStatus> status) {
      this.status = status;
      return this;
    }

    public Builder status(ListJobsRequestStatus status) {
      this.status = Optional.ofNullable(status);
      return this;
    }

    @JsonSetter(
        value = "page",
        nulls = Nulls.SKIP
    )
    public Builder page(Optional<Double> page) {
      this.page = page;
      return this;
    }

    public Builder page(Double page) {
      this.page = Optional.ofNullable(page);
      return this;
    }

    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Double> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Double limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    public ListJobsRequest build() {
      return new ListJobsRequest(type, status, page, limit, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
