/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.webhooks;

import com.berrycrawl.core.ClientOptions;
import com.berrycrawl.core.RequestOptions;
import com.berrycrawl.resources.webhooks.requests.CreateWebhookDto;
import com.berrycrawl.resources.webhooks.requests.DeleteWebhooksRequest;
import com.berrycrawl.resources.webhooks.requests.GetWebhooksRequest;
import com.berrycrawl.resources.webhooks.requests.TestWebhookDto;
import com.berrycrawl.resources.webhooks.requests.UpdateWebhookDto;
import com.berrycrawl.types.ListWebhooksResponse;
import com.berrycrawl.types.MessageResponse;
import com.berrycrawl.types.TestWebhookResponse;
import com.berrycrawl.types.WebhookResponse;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncWebhooksClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawWebhooksClient rawClient;

  public AsyncWebhooksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawWebhooksClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawWebhooksClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<ListWebhooksResponse> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  public CompletableFuture<ListWebhooksResponse> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> create(CreateWebhookDto request) {
    return this.rawClient.create(request).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> create(CreateWebhookDto request,
      RequestOptions requestOptions) {
    return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> get(String id) {
    return this.rawClient.get(id).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> get(String id, GetWebhooksRequest request) {
    return this.rawClient.get(id, request).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> get(String id, GetWebhooksRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(id, request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<MessageResponse> delete(String id) {
    return this.rawClient.delete(id).thenApply(response -> response.body());
  }

  public CompletableFuture<MessageResponse> delete(String id, RequestOptions requestOptions) {
    return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<MessageResponse> delete(String id, DeleteWebhooksRequest request) {
    return this.rawClient.delete(id, request).thenApply(response -> response.body());
  }

  public CompletableFuture<MessageResponse> delete(String id, DeleteWebhooksRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.delete(id, request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> update(String id) {
    return this.rawClient.update(id).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> update(String id, RequestOptions requestOptions) {
    return this.rawClient.update(id, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> update(String id, UpdateWebhookDto request) {
    return this.rawClient.update(id, request).thenApply(response -> response.body());
  }

  public CompletableFuture<WebhookResponse> update(String id, UpdateWebhookDto request,
      RequestOptions requestOptions) {
    return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<TestWebhookResponse> test(String id, TestWebhookDto request) {
    return this.rawClient.test(id, request).thenApply(response -> response.body());
  }

  public CompletableFuture<TestWebhookResponse> test(String id, TestWebhookDto request,
      RequestOptions requestOptions) {
    return this.rawClient.test(id, request, requestOptions).thenApply(response -> response.body());
  }
}
