/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.webhooks;

import com.berrycrawl.core.BerrycrawlApiException;
import com.berrycrawl.core.BerrycrawlException;
import com.berrycrawl.core.BerrycrawlHttpResponse;
import com.berrycrawl.core.ClientOptions;
import com.berrycrawl.core.MediaTypes;
import com.berrycrawl.core.ObjectMappers;
import com.berrycrawl.core.RequestOptions;
import com.berrycrawl.core.RetryInterceptor;
import com.berrycrawl.resources.webhooks.requests.CreateWebhookDto;
import com.berrycrawl.resources.webhooks.requests.DeleteWebhooksRequest;
import com.berrycrawl.resources.webhooks.requests.GetWebhooksRequest;
import com.berrycrawl.resources.webhooks.requests.TestWebhookDto;
import com.berrycrawl.resources.webhooks.requests.UpdateWebhookDto;
import com.berrycrawl.types.ListWebhooksResponse;
import com.berrycrawl.types.MessageResponse;
import com.berrycrawl.types.TestWebhookResponse;
import com.berrycrawl.types.WebhookResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawWebhooksClient {
  protected final ClientOptions clientOptions;

  public RawWebhooksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public BerrycrawlHttpResponse<ListWebhooksResponse> list() {
    return list(null);
  }

  public BerrycrawlHttpResponse<ListWebhooksResponse> list(RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("webhooks");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListWebhooksResponse.class), response);
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (JsonProcessingException e) {
        throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
      }
      catch (IOException e) {
        throw new BerrycrawlException("Network error executing HTTP request", e);
      }
    }

    public BerrycrawlHttpResponse<WebhookResponse> create(CreateWebhookDto request) {
      return create(request,null);
    }

    public BerrycrawlHttpResponse<WebhookResponse> create(CreateWebhookDto request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("webhooks");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new BerrycrawlException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, WebhookResponse.class), response);
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (JsonProcessingException e) {
          throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
        }
        catch (IOException e) {
          throw new BerrycrawlException("Network error executing HTTP request", e);
        }
      }

      public BerrycrawlHttpResponse<WebhookResponse> get(String id) {
        return get(id,GetWebhooksRequest.builder().build());
      }

      public BerrycrawlHttpResponse<WebhookResponse> get(String id, RequestOptions requestOptions) {
        return get(id,GetWebhooksRequest.builder().build(),requestOptions);
      }

      public BerrycrawlHttpResponse<WebhookResponse> get(String id, GetWebhooksRequest request) {
        return get(id,request,null);
      }

      public BerrycrawlHttpResponse<WebhookResponse> get(String id, GetWebhooksRequest request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("webhooks")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, WebhookResponse.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (JsonProcessingException e) {
            throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
          }
          catch (IOException e) {
            throw new BerrycrawlException("Network error executing HTTP request", e);
          }
        }

        public BerrycrawlHttpResponse<MessageResponse> delete(String id) {
          return delete(id,DeleteWebhooksRequest.builder().build());
        }

        public BerrycrawlHttpResponse<MessageResponse> delete(String id,
            RequestOptions requestOptions) {
          return delete(id,DeleteWebhooksRequest.builder().build(),requestOptions);
        }

        public BerrycrawlHttpResponse<MessageResponse> delete(String id,
            DeleteWebhooksRequest request) {
          return delete(id,request,null);
        }

        public BerrycrawlHttpResponse<MessageResponse> delete(String id,
            DeleteWebhooksRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("webhooks")
            .addPathSegment(id);if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("DELETE", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
              okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MessageResponse.class), response);
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (JsonProcessingException e) {
              throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
            }
            catch (IOException e) {
              throw new BerrycrawlException("Network error executing HTTP request", e);
            }
          }

          public BerrycrawlHttpResponse<WebhookResponse> update(String id) {
            return update(id,UpdateWebhookDto.builder().build());
          }

          public BerrycrawlHttpResponse<WebhookResponse> update(String id,
              RequestOptions requestOptions) {
            return update(id,UpdateWebhookDto.builder().build(),requestOptions);
          }

          public BerrycrawlHttpResponse<WebhookResponse> update(String id,
              UpdateWebhookDto request) {
            return update(id,request,null);
          }

          public BerrycrawlHttpResponse<WebhookResponse> update(String id, UpdateWebhookDto request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("webhooks")
              .addPathSegment(id);if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
              }
              catch(JsonProcessingException e) {
                throw new BerrycrawlException("Failed to serialize request", e);
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, WebhookResponse.class), response);
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (JsonProcessingException e) {
                throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
              }
              catch (IOException e) {
                throw new BerrycrawlException("Network error executing HTTP request", e);
              }
            }

            public BerrycrawlHttpResponse<TestWebhookResponse> test(String id,
                TestWebhookDto request) {
              return test(id,request,null);
            }

            public BerrycrawlHttpResponse<TestWebhookResponse> test(String id,
                TestWebhookDto request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("webhooks")
                .addPathSegment(id)
                .addPathSegments("test");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                }
                catch(JsonProcessingException e) {
                  throw new BerrycrawlException("Failed to serialize request", e);
                }
                Request okhttpRequest = new Request.Builder()
                  .url(httpUrl.build())
                  .method("POST", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json")
                  .build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                  okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, TestWebhookResponse.class), response);
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (JsonProcessingException e) {
                  throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
                }
                catch (IOException e) {
                  throw new BerrycrawlException("Network error executing HTTP request", e);
                }
              }
            }
