/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.core;

import java.lang.Exception;
import java.lang.RuntimeException;
import java.lang.String;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class BerrycrawlException extends RuntimeException {
  public BerrycrawlException(String message) {
    super(message);
  }

  public BerrycrawlException(String message, Exception e) {
    super(message, e);
  }
}
