/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl;

import com.berrycrawl.core.ClientOptions;
import com.berrycrawl.core.RequestOptions;
import com.berrycrawl.core.Suppliers;
import com.berrycrawl.requests.CrawlDto;
import com.berrycrawl.requests.ExtractDto;
import com.berrycrawl.requests.MapDto;
import com.berrycrawl.requests.ParseDto;
import com.berrycrawl.requests.ScrapeDto;
import com.berrycrawl.requests.ScreenshotDto;
import com.berrycrawl.requests.SearchDto;
import com.berrycrawl.resources.account.AccountClient;
import com.berrycrawl.resources.brand.BrandClient;
import com.berrycrawl.resources.jobs.JobsClient;
import com.berrycrawl.resources.webhooks.WebhooksClient;
import com.berrycrawl.types.JobCreatedResponse;
import com.berrycrawl.types.MapResponse;
import com.berrycrawl.types.ScrapeResponse;
import com.berrycrawl.types.SearchResponse;
import java.util.function.Supplier;

public class Berrycrawl {
  protected final ClientOptions clientOptions;

  private final RawBerrycrawl rawClient;

  protected final Supplier<AccountClient> accountClient;

  protected final Supplier<BrandClient> brandClient;

  protected final Supplier<JobsClient> jobsClient;

  protected final Supplier<WebhooksClient> webhooksClient;

  public Berrycrawl(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawBerrycrawl(clientOptions);
    this.accountClient = Suppliers.memoize(() -> new AccountClient(clientOptions));
    this.brandClient = Suppliers.memoize(() -> new BrandClient(clientOptions));
    this.jobsClient = Suppliers.memoize(() -> new JobsClient(clientOptions));
    this.webhooksClient = Suppliers.memoize(() -> new WebhooksClient(clientOptions));
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawBerrycrawl withRawResponse() {
    return this.rawClient;
  }

  public JobCreatedResponse crawl(CrawlDto request) {
    return this.rawClient.crawl(request).body();
  }

  public JobCreatedResponse crawl(CrawlDto request, RequestOptions requestOptions) {
    return this.rawClient.crawl(request, requestOptions).body();
  }

  public JobCreatedResponse extract(ExtractDto request) {
    return this.rawClient.extract(request).body();
  }

  public JobCreatedResponse extract(ExtractDto request, RequestOptions requestOptions) {
    return this.rawClient.extract(request, requestOptions).body();
  }

  public MapResponse map(MapDto request) {
    return this.rawClient.map(request).body();
  }

  public MapResponse map(MapDto request, RequestOptions requestOptions) {
    return this.rawClient.map(request, requestOptions).body();
  }

  public ScrapeResponse parse(ParseDto request) {
    return this.rawClient.parse(request).body();
  }

  public ScrapeResponse parse(ParseDto request, RequestOptions requestOptions) {
    return this.rawClient.parse(request, requestOptions).body();
  }

  public ScrapeResponse scrape() {
    return this.rawClient.scrape().body();
  }

  public ScrapeResponse scrape(RequestOptions requestOptions) {
    return this.rawClient.scrape(requestOptions).body();
  }

  public ScrapeResponse scrape(ScrapeDto request) {
    return this.rawClient.scrape(request).body();
  }

  public ScrapeResponse scrape(ScrapeDto request, RequestOptions requestOptions) {
    return this.rawClient.scrape(request, requestOptions).body();
  }

  /**
   * Cookie banners, blocking overlays, chat widgets, and lazy loading are handled by default. Every cleanup pass can be controlled per request.
   */
  public ScrapeResponse screenshot(ScreenshotDto request) {
    return this.rawClient.screenshot(request).body();
  }

  /**
   * Cookie banners, blocking overlays, chat widgets, and lazy loading are handled by default. Every cleanup pass can be controlled per request.
   */
  public ScrapeResponse screenshot(ScreenshotDto request, RequestOptions requestOptions) {
    return this.rawClient.screenshot(request, requestOptions).body();
  }

  public SearchResponse search(SearchDto request) {
    return this.rawClient.search(request).body();
  }

  public SearchResponse search(SearchDto request, RequestOptions requestOptions) {
    return this.rawClient.search(request, requestOptions).body();
  }

  public AccountClient account() {
    return this.accountClient.get();
  }

  public BrandClient brand() {
    return this.brandClient.get();
  }

  public JobsClient jobs() {
    return this.jobsClient.get();
  }

  public WebhooksClient webhooks() {
    return this.webhooksClient.get();
  }

  public static BerrycrawlBuilder builder() {
    return new BerrycrawlBuilder();
  }
}
