/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl;

import com.berrycrawl.core.BerrycrawlApiException;
import com.berrycrawl.core.BerrycrawlException;
import com.berrycrawl.core.BerrycrawlHttpResponse;
import com.berrycrawl.core.ClientOptions;
import com.berrycrawl.core.MediaTypes;
import com.berrycrawl.core.ObjectMappers;
import com.berrycrawl.core.RequestOptions;
import com.berrycrawl.core.RetryInterceptor;
import com.berrycrawl.errors.BadRequestError;
import com.berrycrawl.errors.TooManyRequestsError;
import com.berrycrawl.errors.UnauthorizedError;
import com.berrycrawl.requests.CrawlDto;
import com.berrycrawl.requests.ExtractDto;
import com.berrycrawl.requests.MapDto;
import com.berrycrawl.requests.ParseDto;
import com.berrycrawl.requests.ScrapeDto;
import com.berrycrawl.requests.ScreenshotDto;
import com.berrycrawl.requests.SearchDto;
import com.berrycrawl.types.JobCreatedResponse;
import com.berrycrawl.types.MapResponse;
import com.berrycrawl.types.ScrapeResponse;
import com.berrycrawl.types.SearchResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawBerrycrawl {
  protected final ClientOptions clientOptions;

  public RawBerrycrawl(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public BerrycrawlHttpResponse<JobCreatedResponse> crawl(CrawlDto request) {
    return crawl(request,null);
  }

  public BerrycrawlHttpResponse<JobCreatedResponse> crawl(CrawlDto request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("crawl");if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      RequestBody body;
      try {
        body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
      }
      catch(JsonProcessingException e) {
        throw new BerrycrawlException("Failed to serialize request", e);
      }
      Request okhttpRequest = new Request.Builder()
        .url(httpUrl.build())
        .method("POST", body)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, JobCreatedResponse.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (JsonProcessingException e) {
        throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
      }
      catch (IOException e) {
        throw new BerrycrawlException("Network error executing HTTP request", e);
      }
    }

    public BerrycrawlHttpResponse<JobCreatedResponse> extract(ExtractDto request) {
      return extract(request,null);
    }

    public BerrycrawlHttpResponse<JobCreatedResponse> extract(ExtractDto request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("extract");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new BerrycrawlException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, JobCreatedResponse.class), response);
          }
          try {
            switch (response.code()) {
              case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (JsonProcessingException e) {
          throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
        }
        catch (IOException e) {
          throw new BerrycrawlException("Network error executing HTTP request", e);
        }
      }

      public BerrycrawlHttpResponse<MapResponse> map(MapDto request) {
        return map(request,null);
      }

      public BerrycrawlHttpResponse<MapResponse> map(MapDto request,
          RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("map");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new BerrycrawlException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MapResponse.class), response);
            }
            try {
              if (response.code() == 401) {
                throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (JsonProcessingException e) {
            throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
          }
          catch (IOException e) {
            throw new BerrycrawlException("Network error executing HTTP request", e);
          }
        }

        public BerrycrawlHttpResponse<ScrapeResponse> parse(ParseDto request) {
          return parse(request,null);
        }

        public BerrycrawlHttpResponse<ScrapeResponse> parse(ParseDto request,
            RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("parse");if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            RequestBody body;
            try {
              body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
            }
            catch(JsonProcessingException e) {
              throw new BerrycrawlException("Failed to serialize request", e);
            }
            Request okhttpRequest = new Request.Builder()
              .url(httpUrl.build())
              .method("POST", body)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Content-Type", "application/json")
              .addHeader("Accept", "application/json")
              .build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
              okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ScrapeResponse.class), response);
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (JsonProcessingException e) {
              throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
            }
            catch (IOException e) {
              throw new BerrycrawlException("Network error executing HTTP request", e);
            }
          }

          public BerrycrawlHttpResponse<ScrapeResponse> scrape() {
            return scrape(ScrapeDto.builder().build());
          }

          public BerrycrawlHttpResponse<ScrapeResponse> scrape(RequestOptions requestOptions) {
            return scrape(ScrapeDto.builder().build(),requestOptions);
          }

          public BerrycrawlHttpResponse<ScrapeResponse> scrape(ScrapeDto request) {
            return scrape(request,null);
          }

          public BerrycrawlHttpResponse<ScrapeResponse> scrape(ScrapeDto request,
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("scrape");if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              RequestBody body;
              try {
                body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
              }
              catch(JsonProcessingException e) {
                throw new BerrycrawlException("Failed to serialize request", e);
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ScrapeResponse.class), response);
                }
                try {
                  switch (response.code()) {
                    case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 429:throw new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (JsonProcessingException e) {
                throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
              }
              catch (IOException e) {
                throw new BerrycrawlException("Network error executing HTTP request", e);
              }
            }

            /**
             * Cookie banners, blocking overlays, chat widgets, and lazy loading are handled by default. Every cleanup pass can be controlled per request.
             */
            public BerrycrawlHttpResponse<ScrapeResponse> screenshot(ScreenshotDto request) {
              return screenshot(request,null);
            }

            /**
             * Cookie banners, blocking overlays, chat widgets, and lazy loading are handled by default. Every cleanup pass can be controlled per request.
             */
            public BerrycrawlHttpResponse<ScrapeResponse> screenshot(ScreenshotDto request,
                RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("screenshot");if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                RequestBody body;
                try {
                  body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                }
                catch(JsonProcessingException e) {
                  throw new BerrycrawlException("Failed to serialize request", e);
                }
                Request okhttpRequest = new Request.Builder()
                  .url(httpUrl.build())
                  .method("POST", body)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Content-Type", "application/json")
                  .addHeader("Accept", "application/json")
                  .build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                  okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ScrapeResponse.class), response);
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (JsonProcessingException e) {
                  throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
                }
                catch (IOException e) {
                  throw new BerrycrawlException("Network error executing HTTP request", e);
                }
              }

              public BerrycrawlHttpResponse<SearchResponse> search(SearchDto request) {
                return search(request,null);
              }

              public BerrycrawlHttpResponse<SearchResponse> search(SearchDto request,
                  RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("search");if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  RequestBody body;
                  try {
                    body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
                  }
                  catch(JsonProcessingException e) {
                    throw new BerrycrawlException("Failed to serialize request", e);
                  }
                  Request okhttpRequest = new Request.Builder()
                    .url(httpUrl.build())
                    .method("POST", body)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Content-Type", "application/json")
                    .addHeader("Accept", "application/json")
                    .build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
                    okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
                  }
                  try (Response response = client.newCall(okhttpRequest).execute()) {
                    ResponseBody responseBody = response.body();
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      return new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SearchResponse.class), response);
                    }
                    try {
                      if (response.code() == 401) {
                        throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    throw new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                  }
                  catch (JsonProcessingException e) {
                    throw new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e);
                  }
                  catch (IOException e) {
                    throw new BerrycrawlException("Network error executing HTTP request", e);
                  }
                }
              }
