/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.jobs;

import com.berrycrawl.core.ClientOptions;
import com.berrycrawl.core.RequestOptions;
import com.berrycrawl.resources.jobs.requests.CancelJobsRequest;
import com.berrycrawl.resources.jobs.requests.GetJobsRequest;
import com.berrycrawl.resources.jobs.requests.ListJobsRequest;
import com.berrycrawl.types.CancelJobResponse;
import com.berrycrawl.types.JobResponse;
import com.berrycrawl.types.ListJobsResponse;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncJobsClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawJobsClient rawClient;

  public AsyncJobsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawJobsClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawJobsClient withRawResponse() {
    return this.rawClient;
  }

  public CompletableFuture<ListJobsResponse> list() {
    return this.rawClient.list().thenApply(response -> response.body());
  }

  public CompletableFuture<ListJobsResponse> list(RequestOptions requestOptions) {
    return this.rawClient.list(requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<ListJobsResponse> list(ListJobsRequest request) {
    return this.rawClient.list(request).thenApply(response -> response.body());
  }

  public CompletableFuture<ListJobsResponse> list(ListJobsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<JobResponse> get(String id) {
    return this.rawClient.get(id).thenApply(response -> response.body());
  }

  public CompletableFuture<JobResponse> get(String id, RequestOptions requestOptions) {
    return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<JobResponse> get(String id, GetJobsRequest request) {
    return this.rawClient.get(id, request).thenApply(response -> response.body());
  }

  public CompletableFuture<JobResponse> get(String id, GetJobsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.get(id, request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<CancelJobResponse> cancel(String id) {
    return this.rawClient.cancel(id).thenApply(response -> response.body());
  }

  public CompletableFuture<CancelJobResponse> cancel(String id, RequestOptions requestOptions) {
    return this.rawClient.cancel(id, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<CancelJobResponse> cancel(String id, CancelJobsRequest request) {
    return this.rawClient.cancel(id, request).thenApply(response -> response.body());
  }

  public CompletableFuture<CancelJobResponse> cancel(String id, CancelJobsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.cancel(id, request, requestOptions).thenApply(response -> response.body());
  }
}
