/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.jobs;

import com.berrycrawl.core.BerrycrawlApiException;
import com.berrycrawl.core.BerrycrawlException;
import com.berrycrawl.core.BerrycrawlHttpResponse;
import com.berrycrawl.core.ClientOptions;
import com.berrycrawl.core.ObjectMappers;
import com.berrycrawl.core.QueryStringMapper;
import com.berrycrawl.core.RequestOptions;
import com.berrycrawl.core.RetryInterceptor;
import com.berrycrawl.resources.jobs.requests.CancelJobsRequest;
import com.berrycrawl.resources.jobs.requests.GetJobsRequest;
import com.berrycrawl.resources.jobs.requests.ListJobsRequest;
import com.berrycrawl.types.CancelJobResponse;
import com.berrycrawl.types.JobResponse;
import com.berrycrawl.types.ListJobsResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawJobsClient {
  protected final ClientOptions clientOptions;

  public AsyncRawJobsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  public CompletableFuture<BerrycrawlHttpResponse<ListJobsResponse>> list() {
    return list(ListJobsRequest.builder().build());
  }

  public CompletableFuture<BerrycrawlHttpResponse<ListJobsResponse>> list(
      RequestOptions requestOptions) {
    return list(ListJobsRequest.builder().build(),requestOptions);
  }

  public CompletableFuture<BerrycrawlHttpResponse<ListJobsResponse>> list(ListJobsRequest request) {
    return list(request,null);
  }

  public CompletableFuture<BerrycrawlHttpResponse<ListJobsResponse>> list(ListJobsRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("jobs");if (request.getType().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "type", request.getType().get(), false);
      }
      if (request.getStatus().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "status", request.getStatus().get(), false);
      }
      if (request.getPage().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      CompletableFuture<BerrycrawlHttpResponse<ListJobsResponse>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListJobsResponse.class), response));
              return;
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (JsonProcessingException e) {
            future.completeExceptionally(new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e));
          }
          catch (IOException e) {
            future.completeExceptionally(new BerrycrawlException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new BerrycrawlException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    public CompletableFuture<BerrycrawlHttpResponse<JobResponse>> get(String id) {
      return get(id,GetJobsRequest.builder().build());
    }

    public CompletableFuture<BerrycrawlHttpResponse<JobResponse>> get(String id,
        RequestOptions requestOptions) {
      return get(id,GetJobsRequest.builder().build(),requestOptions);
    }

    public CompletableFuture<BerrycrawlHttpResponse<JobResponse>> get(String id,
        GetJobsRequest request) {
      return get(id,request,null);
    }

    public CompletableFuture<BerrycrawlHttpResponse<JobResponse>> get(String id,
        GetJobsRequest request, RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("jobs")
        .addPathSegment(id);if (request.getPage().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getLimit().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
        }
        if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        CompletableFuture<BerrycrawlHttpResponse<JobResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, JobResponse.class), response));
                return;
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (JsonProcessingException e) {
              future.completeExceptionally(new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e));
            }
            catch (IOException e) {
              future.completeExceptionally(new BerrycrawlException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new BerrycrawlException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      public CompletableFuture<BerrycrawlHttpResponse<CancelJobResponse>> cancel(String id) {
        return cancel(id,CancelJobsRequest.builder().build());
      }

      public CompletableFuture<BerrycrawlHttpResponse<CancelJobResponse>> cancel(String id,
          RequestOptions requestOptions) {
        return cancel(id,CancelJobsRequest.builder().build(),requestOptions);
      }

      public CompletableFuture<BerrycrawlHttpResponse<CancelJobResponse>> cancel(String id,
          CancelJobsRequest request) {
        return cancel(id,request,null);
      }

      public CompletableFuture<BerrycrawlHttpResponse<CancelJobResponse>> cancel(String id,
          CancelJobsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("jobs")
          .addPathSegment(id);if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("DELETE", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
          }
          CompletableFuture<BerrycrawlHttpResponse<CancelJobResponse>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new BerrycrawlHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CancelJobResponse.class), response));
                  return;
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new BerrycrawlApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (JsonProcessingException e) {
                future.completeExceptionally(new BerrycrawlException("Failed to deserialize response: " + e.getMessage(), e));
              }
              catch (IOException e) {
                future.completeExceptionally(new BerrycrawlException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new BerrycrawlException("Network error executing HTTP request", e));
            }
          });
          return future;
        }
      }
