/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.requests;

import com.berrycrawl.core.ObjectMappers;
import com.berrycrawl.types.AgentConfigDto;
import com.berrycrawl.types.ExtractWebhookConfigDto;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ExtractDto.Builder.class
)
public final class ExtractDto {
  private final Optional<AgentConfigDto> agent;

  private final Optional<Boolean> enableWebSearch;

  private final Optional<Boolean> ignoreInvalidUrLs;

  private final Optional<Boolean> ignoreSitemap;

  private final Optional<Boolean> includeSubdomains;

  private final String prompt;

  private final Optional<Map<String, Object>> schema;

  private final Optional<Map<String, Object>> scrapeOptions;

  private final Optional<Boolean> showSources;

  private final Optional<List<String>> urls;

  private final Optional<ExtractWebhookConfigDto> webhook;

  private final Map<String, Object> additionalProperties;

  private ExtractDto(Optional<AgentConfigDto> agent, Optional<Boolean> enableWebSearch,
      Optional<Boolean> ignoreInvalidUrLs, Optional<Boolean> ignoreSitemap,
      Optional<Boolean> includeSubdomains, String prompt, Optional<Map<String, Object>> schema,
      Optional<Map<String, Object>> scrapeOptions, Optional<Boolean> showSources,
      Optional<List<String>> urls, Optional<ExtractWebhookConfigDto> webhook,
      Map<String, Object> additionalProperties) {
    this.agent = agent;
    this.enableWebSearch = enableWebSearch;
    this.ignoreInvalidUrLs = ignoreInvalidUrLs;
    this.ignoreSitemap = ignoreSitemap;
    this.includeSubdomains = includeSubdomains;
    this.prompt = prompt;
    this.schema = schema;
    this.scrapeOptions = scrapeOptions;
    this.showSources = showSources;
    this.urls = urls;
    this.webhook = webhook;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Agent configuration
   */
  @JsonProperty("agent")
  public Optional<AgentConfigDto> getAgent() {
    return agent;
  }

  /**
   * @return Enable web search for URL discovery
   */
  @JsonProperty("enableWebSearch")
  public Optional<Boolean> getEnableWebSearch() {
    return enableWebSearch;
  }

  /**
   * @return Ignore invalid URLs and process remaining valid ones
   */
  @JsonProperty("ignoreInvalidURLs")
  public Optional<Boolean> getIgnoreInvalidUrLs() {
    return ignoreInvalidUrLs;
  }

  /**
   * @return Ignore sitemap during URL discovery
   */
  @JsonProperty("ignoreSitemap")
  public Optional<Boolean> getIgnoreSitemap() {
    return ignoreSitemap;
  }

  /**
   * @return Include subdomains in extraction
   */
  @JsonProperty("includeSubdomains")
  public Optional<Boolean> getIncludeSubdomains() {
    return includeSubdomains;
  }

  /**
   * @return Natural language prompt describing what to extract. Maximum 16384 UTF-8 bytes.
   */
  @JsonProperty("prompt")
  public String getPrompt() {
    return prompt;
  }

  /**
   * @return JSON Schema for structured output. Serialized schema is limited to 65536 UTF-8 bytes.
   */
  @JsonProperty("schema")
  public Optional<Map<String, Object>> getSchema() {
    return schema;
  }

  /**
   * @return Scrape options for each URL. zeroDataRetention: true is currently rejected with 400 ZERO_DATA_RETENTION_NOT_SUPPORTED.
   */
  @JsonProperty("scrapeOptions")
  public Optional<Map<String, Object>> getScrapeOptions() {
    return scrapeOptions;
  }

  /**
   * @return Include source citations in response
   */
  @JsonProperty("showSources")
  public Optional<Boolean> getShowSources() {
    return showSources;
  }

  /**
   * @return 1–20 unique public HTTP(S) URLs. May be omitted only when enableWebSearch is true. Each URL is limited to 2048 UTF-8 bytes.
   */
  @JsonProperty("urls")
  public Optional<List<String>> getUrls() {
    return urls;
  }

  /**
   * @return Webhook configuration
   */
  @JsonProperty("webhook")
  public Optional<ExtractWebhookConfigDto> getWebhook() {
    return webhook;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ExtractDto && equalTo((ExtractDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ExtractDto other) {
    return agent.equals(other.agent) && enableWebSearch.equals(other.enableWebSearch) && ignoreInvalidUrLs.equals(other.ignoreInvalidUrLs) && ignoreSitemap.equals(other.ignoreSitemap) && includeSubdomains.equals(other.includeSubdomains) && prompt.equals(other.prompt) && schema.equals(other.schema) && scrapeOptions.equals(other.scrapeOptions) && showSources.equals(other.showSources) && urls.equals(other.urls) && webhook.equals(other.webhook);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.agent, this.enableWebSearch, this.ignoreInvalidUrLs, this.ignoreSitemap, this.includeSubdomains, this.prompt, this.schema, this.scrapeOptions, this.showSources, this.urls, this.webhook);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PromptStage builder() {
    return new Builder();
  }

  public interface PromptStage {
    /**
     * <p>Natural language prompt describing what to extract. Maximum 16384 UTF-8 bytes.</p>
     */
    _FinalStage prompt(@NotNull String prompt);

    Builder from(ExtractDto other);
  }

  public interface _FinalStage {
    ExtractDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Agent configuration</p>
     */
    _FinalStage agent(Optional<AgentConfigDto> agent);

    _FinalStage agent(AgentConfigDto agent);

    /**
     * <p>Enable web search for URL discovery</p>
     */
    _FinalStage enableWebSearch(Optional<Boolean> enableWebSearch);

    _FinalStage enableWebSearch(Boolean enableWebSearch);

    /**
     * <p>Ignore invalid URLs and process remaining valid ones</p>
     */
    _FinalStage ignoreInvalidUrLs(Optional<Boolean> ignoreInvalidUrLs);

    _FinalStage ignoreInvalidUrLs(Boolean ignoreInvalidUrLs);

    /**
     * <p>Ignore sitemap during URL discovery</p>
     */
    _FinalStage ignoreSitemap(Optional<Boolean> ignoreSitemap);

    _FinalStage ignoreSitemap(Boolean ignoreSitemap);

    /**
     * <p>Include subdomains in extraction</p>
     */
    _FinalStage includeSubdomains(Optional<Boolean> includeSubdomains);

    _FinalStage includeSubdomains(Boolean includeSubdomains);

    /**
     * <p>JSON Schema for structured output. Serialized schema is limited to 65536 UTF-8 bytes.</p>
     */
    _FinalStage schema(Optional<Map<String, Object>> schema);

    _FinalStage schema(Map<String, Object> schema);

    /**
     * <p>Scrape options for each URL. zeroDataRetention: true is currently rejected with 400 ZERO_DATA_RETENTION_NOT_SUPPORTED.</p>
     */
    _FinalStage scrapeOptions(Optional<Map<String, Object>> scrapeOptions);

    _FinalStage scrapeOptions(Map<String, Object> scrapeOptions);

    /**
     * <p>Include source citations in response</p>
     */
    _FinalStage showSources(Optional<Boolean> showSources);

    _FinalStage showSources(Boolean showSources);

    /**
     * <p>1–20 unique public HTTP(S) URLs. May be omitted only when enableWebSearch is true. Each URL is limited to 2048 UTF-8 bytes.</p>
     */
    _FinalStage urls(Optional<List<String>> urls);

    _FinalStage urls(List<String> urls);

    /**
     * <p>Webhook configuration</p>
     */
    _FinalStage webhook(Optional<ExtractWebhookConfigDto> webhook);

    _FinalStage webhook(ExtractWebhookConfigDto webhook);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PromptStage, _FinalStage {
    private String prompt;

    private Optional<ExtractWebhookConfigDto> webhook = Optional.empty();

    private Optional<List<String>> urls = Optional.empty();

    private Optional<Boolean> showSources = Optional.empty();

    private Optional<Map<String, Object>> scrapeOptions = Optional.empty();

    private Optional<Map<String, Object>> schema = Optional.empty();

    private Optional<Boolean> includeSubdomains = Optional.empty();

    private Optional<Boolean> ignoreSitemap = Optional.empty();

    private Optional<Boolean> ignoreInvalidUrLs = Optional.empty();

    private Optional<Boolean> enableWebSearch = Optional.empty();

    private Optional<AgentConfigDto> agent = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ExtractDto other) {
      agent(other.getAgent());
      enableWebSearch(other.getEnableWebSearch());
      ignoreInvalidUrLs(other.getIgnoreInvalidUrLs());
      ignoreSitemap(other.getIgnoreSitemap());
      includeSubdomains(other.getIncludeSubdomains());
      prompt(other.getPrompt());
      schema(other.getSchema());
      scrapeOptions(other.getScrapeOptions());
      showSources(other.getShowSources());
      urls(other.getUrls());
      webhook(other.getWebhook());
      return this;
    }

    /**
     * <p>Natural language prompt describing what to extract. Maximum 16384 UTF-8 bytes.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("prompt")
    public _FinalStage prompt(@NotNull String prompt) {
      this.prompt = Objects.requireNonNull(prompt, "prompt must not be null");
      return this;
    }

    /**
     * <p>Webhook configuration</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage webhook(ExtractWebhookConfigDto webhook) {
      this.webhook = Optional.ofNullable(webhook);
      return this;
    }

    /**
     * <p>Webhook configuration</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "webhook",
        nulls = Nulls.SKIP
    )
    public _FinalStage webhook(Optional<ExtractWebhookConfigDto> webhook) {
      this.webhook = webhook;
      return this;
    }

    /**
     * <p>1–20 unique public HTTP(S) URLs. May be omitted only when enableWebSearch is true. Each URL is limited to 2048 UTF-8 bytes.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage urls(List<String> urls) {
      this.urls = Optional.ofNullable(urls);
      return this;
    }

    /**
     * <p>1–20 unique public HTTP(S) URLs. May be omitted only when enableWebSearch is true. Each URL is limited to 2048 UTF-8 bytes.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "urls",
        nulls = Nulls.SKIP
    )
    public _FinalStage urls(Optional<List<String>> urls) {
      this.urls = urls;
      return this;
    }

    /**
     * <p>Include source citations in response</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage showSources(Boolean showSources) {
      this.showSources = Optional.ofNullable(showSources);
      return this;
    }

    /**
     * <p>Include source citations in response</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "showSources",
        nulls = Nulls.SKIP
    )
    public _FinalStage showSources(Optional<Boolean> showSources) {
      this.showSources = showSources;
      return this;
    }

    /**
     * <p>Scrape options for each URL. zeroDataRetention: true is currently rejected with 400 ZERO_DATA_RETENTION_NOT_SUPPORTED.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage scrapeOptions(Map<String, Object> scrapeOptions) {
      this.scrapeOptions = Optional.ofNullable(scrapeOptions);
      return this;
    }

    /**
     * <p>Scrape options for each URL. zeroDataRetention: true is currently rejected with 400 ZERO_DATA_RETENTION_NOT_SUPPORTED.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "scrapeOptions",
        nulls = Nulls.SKIP
    )
    public _FinalStage scrapeOptions(Optional<Map<String, Object>> scrapeOptions) {
      this.scrapeOptions = scrapeOptions;
      return this;
    }

    /**
     * <p>JSON Schema for structured output. Serialized schema is limited to 65536 UTF-8 bytes.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage schema(Map<String, Object> schema) {
      this.schema = Optional.ofNullable(schema);
      return this;
    }

    /**
     * <p>JSON Schema for structured output. Serialized schema is limited to 65536 UTF-8 bytes.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "schema",
        nulls = Nulls.SKIP
    )
    public _FinalStage schema(Optional<Map<String, Object>> schema) {
      this.schema = schema;
      return this;
    }

    /**
     * <p>Include subdomains in extraction</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage includeSubdomains(Boolean includeSubdomains) {
      this.includeSubdomains = Optional.ofNullable(includeSubdomains);
      return this;
    }

    /**
     * <p>Include subdomains in extraction</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "includeSubdomains",
        nulls = Nulls.SKIP
    )
    public _FinalStage includeSubdomains(Optional<Boolean> includeSubdomains) {
      this.includeSubdomains = includeSubdomains;
      return this;
    }

    /**
     * <p>Ignore sitemap during URL discovery</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage ignoreSitemap(Boolean ignoreSitemap) {
      this.ignoreSitemap = Optional.ofNullable(ignoreSitemap);
      return this;
    }

    /**
     * <p>Ignore sitemap during URL discovery</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "ignoreSitemap",
        nulls = Nulls.SKIP
    )
    public _FinalStage ignoreSitemap(Optional<Boolean> ignoreSitemap) {
      this.ignoreSitemap = ignoreSitemap;
      return this;
    }

    /**
     * <p>Ignore invalid URLs and process remaining valid ones</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage ignoreInvalidUrLs(Boolean ignoreInvalidUrLs) {
      this.ignoreInvalidUrLs = Optional.ofNullable(ignoreInvalidUrLs);
      return this;
    }

    /**
     * <p>Ignore invalid URLs and process remaining valid ones</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "ignoreInvalidURLs",
        nulls = Nulls.SKIP
    )
    public _FinalStage ignoreInvalidUrLs(Optional<Boolean> ignoreInvalidUrLs) {
      this.ignoreInvalidUrLs = ignoreInvalidUrLs;
      return this;
    }

    /**
     * <p>Enable web search for URL discovery</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage enableWebSearch(Boolean enableWebSearch) {
      this.enableWebSearch = Optional.ofNullable(enableWebSearch);
      return this;
    }

    /**
     * <p>Enable web search for URL discovery</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "enableWebSearch",
        nulls = Nulls.SKIP
    )
    public _FinalStage enableWebSearch(Optional<Boolean> enableWebSearch) {
      this.enableWebSearch = enableWebSearch;
      return this;
    }

    /**
     * <p>Agent configuration</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage agent(AgentConfigDto agent) {
      this.agent = Optional.ofNullable(agent);
      return this;
    }

    /**
     * <p>Agent configuration</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "agent",
        nulls = Nulls.SKIP
    )
    public _FinalStage agent(Optional<AgentConfigDto> agent) {
      this.agent = agent;
      return this;
    }

    @java.lang.Override
    public ExtractDto build() {
      return new ExtractDto(agent, enableWebSearch, ignoreInvalidUrLs, ignoreSitemap, includeSubdomains, prompt, schema, scrapeOptions, showSources, urls, webhook, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
