/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.requests;

import com.berrycrawl.core.ObjectMappers;
import com.berrycrawl.types.ScreenshotClipDto;
import com.berrycrawl.types.ScreenshotCookieDto;
import com.berrycrawl.types.ScreenshotDtoColorScheme;
import com.berrycrawl.types.ScreenshotDtoDevice;
import com.berrycrawl.types.ScreenshotDtoFormat;
import com.berrycrawl.types.ScreenshotDtoFullPageAlgorithm;
import com.berrycrawl.types.ScreenshotDtoProxy;
import com.berrycrawl.types.ScreenshotDtoResponseFormat;
import com.berrycrawl.types.ScreenshotDtoScale;
import com.berrycrawl.types.ScreenshotDtoWaitUntil;
import com.berrycrawl.types.ScreenshotLocationDto;
import com.berrycrawl.types.ScreenshotViewportDto;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScreenshotDto.Builder.class
)
public final class ScreenshotDto {
  private final Optional<Boolean> blockAds;

  private final Optional<String> clickSelector;

  private final Optional<ScreenshotClipDto> clip;

  private final Optional<ScreenshotDtoColorScheme> colorScheme;

  private final Optional<List<ScreenshotCookieDto>> cookies;

  private final Optional<Double> delay;

  private final Optional<ScreenshotDtoDevice> device;

  private final Optional<Boolean> disableAnimations;

  private final Optional<ScreenshotDtoFormat> format;

  private final Optional<Boolean> fullPage;

  private final Optional<ScreenshotDtoFullPageAlgorithm> fullPageAlgorithm;

  private final Optional<Map<String, Object>> headers;

  private final Optional<Boolean> hideFixedElements;

  private final Optional<List<String>> hideSelectors;

  private final Optional<ScreenshotLocationDto> location;

  private final Optional<String> maskColor;

  private final Optional<List<String>> maskSelectors;

  private final Optional<Double> maxHeight;

  private final Optional<Boolean> omitBackground;

  private final Optional<ScreenshotDtoProxy> proxy;

  private final Optional<Double> quality;

  private final Optional<Boolean> reducedMotion;

  private final Optional<Boolean> removeChatWidgets;

  private final Optional<Boolean> removeCookieBanners;

  private final Optional<Boolean> removeOverlays;

  private final Optional<ScreenshotDtoResponseFormat> responseFormat;

  private final Optional<ScreenshotDtoScale> scale;

  private final Optional<Double> scrollDelay;

  private final Optional<Boolean> scrollPage;

  private final Optional<String> selector;

  private final Optional<List<String>> styles;

  private final Optional<Double> timeout;

  private final String url;

  private final Optional<ScreenshotViewportDto> viewport;

  private final Optional<String> waitForSelector;

  private final Optional<ScreenshotDtoWaitUntil> waitUntil;

  private final Map<String, Object> additionalProperties;

  private ScreenshotDto(Optional<Boolean> blockAds, Optional<String> clickSelector,
      Optional<ScreenshotClipDto> clip, Optional<ScreenshotDtoColorScheme> colorScheme,
      Optional<List<ScreenshotCookieDto>> cookies, Optional<Double> delay,
      Optional<ScreenshotDtoDevice> device, Optional<Boolean> disableAnimations,
      Optional<ScreenshotDtoFormat> format, Optional<Boolean> fullPage,
      Optional<ScreenshotDtoFullPageAlgorithm> fullPageAlgorithm,
      Optional<Map<String, Object>> headers, Optional<Boolean> hideFixedElements,
      Optional<List<String>> hideSelectors, Optional<ScreenshotLocationDto> location,
      Optional<String> maskColor, Optional<List<String>> maskSelectors, Optional<Double> maxHeight,
      Optional<Boolean> omitBackground, Optional<ScreenshotDtoProxy> proxy,
      Optional<Double> quality, Optional<Boolean> reducedMotion,
      Optional<Boolean> removeChatWidgets, Optional<Boolean> removeCookieBanners,
      Optional<Boolean> removeOverlays, Optional<ScreenshotDtoResponseFormat> responseFormat,
      Optional<ScreenshotDtoScale> scale, Optional<Double> scrollDelay,
      Optional<Boolean> scrollPage, Optional<String> selector, Optional<List<String>> styles,
      Optional<Double> timeout, String url, Optional<ScreenshotViewportDto> viewport,
      Optional<String> waitForSelector, Optional<ScreenshotDtoWaitUntil> waitUntil,
      Map<String, Object> additionalProperties) {
    this.blockAds = blockAds;
    this.clickSelector = clickSelector;
    this.clip = clip;
    this.colorScheme = colorScheme;
    this.cookies = cookies;
    this.delay = delay;
    this.device = device;
    this.disableAnimations = disableAnimations;
    this.format = format;
    this.fullPage = fullPage;
    this.fullPageAlgorithm = fullPageAlgorithm;
    this.headers = headers;
    this.hideFixedElements = hideFixedElements;
    this.hideSelectors = hideSelectors;
    this.location = location;
    this.maskColor = maskColor;
    this.maskSelectors = maskSelectors;
    this.maxHeight = maxHeight;
    this.omitBackground = omitBackground;
    this.proxy = proxy;
    this.quality = quality;
    this.reducedMotion = reducedMotion;
    this.removeChatWidgets = removeChatWidgets;
    this.removeCookieBanners = removeCookieBanners;
    this.removeOverlays = removeOverlays;
    this.responseFormat = responseFormat;
    this.scale = scale;
    this.scrollDelay = scrollDelay;
    this.scrollPage = scrollPage;
    this.selector = selector;
    this.styles = styles;
    this.timeout = timeout;
    this.url = url;
    this.viewport = viewport;
    this.waitForSelector = waitForSelector;
    this.waitUntil = waitUntil;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Block common advertising and analytics requests
   */
  @JsonProperty("blockAds")
  public Optional<Boolean> getBlockAds() {
    return blockAds;
  }

  /**
   * @return Click this CSS selector before capture
   */
  @JsonProperty("clickSelector")
  public Optional<String> getClickSelector() {
    return clickSelector;
  }

  /**
   * @return Capture an exact pixel rectangle instead of the page
   */
  @JsonProperty("clip")
  public Optional<ScreenshotClipDto> getClip() {
    return clip;
  }

  @JsonProperty("colorScheme")
  public Optional<ScreenshotDtoColorScheme> getColorScheme() {
    return colorScheme;
  }

  /**
   * @return Cookies to set before loading the page
   */
  @JsonProperty("cookies")
  public Optional<List<ScreenshotCookieDto>> getCookies() {
    return cookies;
  }

  /**
   * @return Extra settling time after the page is ready, in milliseconds
   */
  @JsonProperty("delay")
  public Optional<Double> getDelay() {
    return delay;
  }

  /**
   * @return Named viewport preset
   */
  @JsonProperty("device")
  public Optional<ScreenshotDtoDevice> getDevice() {
    return device;
  }

  @JsonProperty("disableAnimations")
  public Optional<Boolean> getDisableAnimations() {
    return disableAnimations;
  }

  @JsonProperty("format")
  public Optional<ScreenshotDtoFormat> getFormat() {
    return format;
  }

  /**
   * @return Capture the complete page instead of only the viewport
   */
  @JsonProperty("fullPage")
  public Optional<Boolean> getFullPage() {
    return fullPage;
  }

  /**
   * @return auto uses native capture for normal pages and stitched slices for very tall pages
   */
  @JsonProperty("fullPageAlgorithm")
  public Optional<ScreenshotDtoFullPageAlgorithm> getFullPageAlgorithm() {
    return fullPageAlgorithm;
  }

  /**
   * @return Headers sent while loading the page
   */
  @JsonProperty("headers")
  public Optional<Map<String, Object>> getHeaders() {
    return headers;
  }

  /**
   * @return Show fixed/sticky UI once instead of repeating it in stitched captures
   */
  @JsonProperty("hideFixedElements")
  public Optional<Boolean> getHideFixedElements() {
    return hideFixedElements;
  }

  /**
   * @return Hide matching elements before capture
   */
  @JsonProperty("hideSelectors")
  public Optional<List<String>> getHideSelectors() {
    return hideSelectors;
  }

  @JsonProperty("location")
  public Optional<ScreenshotLocationDto> getLocation() {
    return location;
  }

  @JsonProperty("maskColor")
  public Optional<String> getMaskColor() {
    return maskColor;
  }

  /**
   * @return Cover matching elements with a solid privacy mask
   */
  @JsonProperty("maskSelectors")
  public Optional<List<String>> getMaskSelectors() {
    return maskSelectors;
  }

  /**
   * @return Maximum full-page height. Prevents endless captures on infinite pages.
   */
  @JsonProperty("maxHeight")
  public Optional<Double> getMaxHeight() {
    return maxHeight;
  }

  /**
   * @return Use a transparent background where the page allows it
   */
  @JsonProperty("omitBackground")
  public Optional<Boolean> getOmitBackground() {
    return omitBackground;
  }

  /**
   * @return Proxy mode
   */
  @JsonProperty("proxy")
  public Optional<ScreenshotDtoProxy> getProxy() {
    return proxy;
  }

  /**
   * @return JPEG or WebP quality
   */
  @JsonProperty("quality")
  public Optional<Double> getQuality() {
    return quality;
  }

  @JsonProperty("reducedMotion")
  public Optional<Boolean> getReducedMotion() {
    return reducedMotion;
  }

  /**
   * @return Hide common support and chat widgets
   */
  @JsonProperty("removeChatWidgets")
  public Optional<Boolean> getRemoveChatWidgets() {
    return removeChatWidgets;
  }

  /**
   * @return Accept known consent dialogs, hide remaining cookie banners, and restore page scrolling
   */
  @JsonProperty("removeCookieBanners")
  public Optional<Boolean> getRemoveCookieBanners() {
    return removeCookieBanners;
  }

  /**
   * @return Remove newsletter gates, modal backdrops, and blocking overlays
   */
  @JsonProperty("removeOverlays")
  public Optional<Boolean> getRemoveOverlays() {
    return removeOverlays;
  }

  /**
   * @return Return a CDN URL or an inline data URL
   */
  @JsonProperty("responseFormat")
  public Optional<ScreenshotDtoResponseFormat> getResponseFormat() {
    return responseFormat;
  }

  /**
   * @return Capture at CSS pixel size or the emulated device pixel ratio
   */
  @JsonProperty("scale")
  public Optional<ScreenshotDtoScale> getScale() {
    return scale;
  }

  /**
   * @return Pause between lazy-load scroll steps, in milliseconds
   */
  @JsonProperty("scrollDelay")
  public Optional<Double> getScrollDelay() {
    return scrollDelay;
  }

  /**
   * @return Scroll through the page first so lazy content is loaded
   */
  @JsonProperty("scrollPage")
  public Optional<Boolean> getScrollPage() {
    return scrollPage;
  }

  /**
   * @return Capture one element instead of the page
   */
  @JsonProperty("selector")
  public Optional<String> getSelector() {
    return selector;
  }

  /**
   * @return CSS rules to apply before capture
   */
  @JsonProperty("styles")
  public Optional<List<String>> getStyles() {
    return styles;
  }

  @JsonProperty("timeout")
  public Optional<Double> getTimeout() {
    return timeout;
  }

  /**
   * @return Public webpage URL to capture
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  /**
   * @return Custom viewport. Overrides the named device dimensions.
   */
  @JsonProperty("viewport")
  public Optional<ScreenshotViewportDto> getViewport() {
    return viewport;
  }

  /**
   * @return Wait for this CSS selector before capture
   */
  @JsonProperty("waitForSelector")
  public Optional<String> getWaitForSelector() {
    return waitForSelector;
  }

  /**
   * @return Page readiness milestone used before capture
   */
  @JsonProperty("waitUntil")
  public Optional<ScreenshotDtoWaitUntil> getWaitUntil() {
    return waitUntil;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScreenshotDto && equalTo((ScreenshotDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScreenshotDto other) {
    return blockAds.equals(other.blockAds) && clickSelector.equals(other.clickSelector) && clip.equals(other.clip) && colorScheme.equals(other.colorScheme) && cookies.equals(other.cookies) && delay.equals(other.delay) && device.equals(other.device) && disableAnimations.equals(other.disableAnimations) && format.equals(other.format) && fullPage.equals(other.fullPage) && fullPageAlgorithm.equals(other.fullPageAlgorithm) && headers.equals(other.headers) && hideFixedElements.equals(other.hideFixedElements) && hideSelectors.equals(other.hideSelectors) && location.equals(other.location) && maskColor.equals(other.maskColor) && maskSelectors.equals(other.maskSelectors) && maxHeight.equals(other.maxHeight) && omitBackground.equals(other.omitBackground) && proxy.equals(other.proxy) && quality.equals(other.quality) && reducedMotion.equals(other.reducedMotion) && removeChatWidgets.equals(other.removeChatWidgets) && removeCookieBanners.equals(other.removeCookieBanners) && removeOverlays.equals(other.removeOverlays) && responseFormat.equals(other.responseFormat) && scale.equals(other.scale) && scrollDelay.equals(other.scrollDelay) && scrollPage.equals(other.scrollPage) && selector.equals(other.selector) && styles.equals(other.styles) && timeout.equals(other.timeout) && url.equals(other.url) && viewport.equals(other.viewport) && waitForSelector.equals(other.waitForSelector) && waitUntil.equals(other.waitUntil);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.blockAds, this.clickSelector, this.clip, this.colorScheme, this.cookies, this.delay, this.device, this.disableAnimations, this.format, this.fullPage, this.fullPageAlgorithm, this.headers, this.hideFixedElements, this.hideSelectors, this.location, this.maskColor, this.maskSelectors, this.maxHeight, this.omitBackground, this.proxy, this.quality, this.reducedMotion, this.removeChatWidgets, this.removeCookieBanners, this.removeOverlays, this.responseFormat, this.scale, this.scrollDelay, this.scrollPage, this.selector, this.styles, this.timeout, this.url, this.viewport, this.waitForSelector, this.waitUntil);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    /**
     * <p>Public webpage URL to capture</p>
     */
    _FinalStage url(@NotNull String url);

    Builder from(ScreenshotDto other);
  }

  public interface _FinalStage {
    ScreenshotDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Block common advertising and analytics requests</p>
     */
    _FinalStage blockAds(Optional<Boolean> blockAds);

    _FinalStage blockAds(Boolean blockAds);

    /**
     * <p>Click this CSS selector before capture</p>
     */
    _FinalStage clickSelector(Optional<String> clickSelector);

    _FinalStage clickSelector(String clickSelector);

    /**
     * <p>Capture an exact pixel rectangle instead of the page</p>
     */
    _FinalStage clip(Optional<ScreenshotClipDto> clip);

    _FinalStage clip(ScreenshotClipDto clip);

    _FinalStage colorScheme(Optional<ScreenshotDtoColorScheme> colorScheme);

    _FinalStage colorScheme(ScreenshotDtoColorScheme colorScheme);

    /**
     * <p>Cookies to set before loading the page</p>
     */
    _FinalStage cookies(Optional<List<ScreenshotCookieDto>> cookies);

    _FinalStage cookies(List<ScreenshotCookieDto> cookies);

    /**
     * <p>Extra settling time after the page is ready, in milliseconds</p>
     */
    _FinalStage delay(Optional<Double> delay);

    _FinalStage delay(Double delay);

    /**
     * <p>Named viewport preset</p>
     */
    _FinalStage device(Optional<ScreenshotDtoDevice> device);

    _FinalStage device(ScreenshotDtoDevice device);

    _FinalStage disableAnimations(Optional<Boolean> disableAnimations);

    _FinalStage disableAnimations(Boolean disableAnimations);

    _FinalStage format(Optional<ScreenshotDtoFormat> format);

    _FinalStage format(ScreenshotDtoFormat format);

    /**
     * <p>Capture the complete page instead of only the viewport</p>
     */
    _FinalStage fullPage(Optional<Boolean> fullPage);

    _FinalStage fullPage(Boolean fullPage);

    /**
     * <p>auto uses native capture for normal pages and stitched slices for very tall pages</p>
     */
    _FinalStage fullPageAlgorithm(Optional<ScreenshotDtoFullPageAlgorithm> fullPageAlgorithm);

    _FinalStage fullPageAlgorithm(ScreenshotDtoFullPageAlgorithm fullPageAlgorithm);

    /**
     * <p>Headers sent while loading the page</p>
     */
    _FinalStage headers(Optional<Map<String, Object>> headers);

    _FinalStage headers(Map<String, Object> headers);

    /**
     * <p>Show fixed/sticky UI once instead of repeating it in stitched captures</p>
     */
    _FinalStage hideFixedElements(Optional<Boolean> hideFixedElements);

    _FinalStage hideFixedElements(Boolean hideFixedElements);

    /**
     * <p>Hide matching elements before capture</p>
     */
    _FinalStage hideSelectors(Optional<List<String>> hideSelectors);

    _FinalStage hideSelectors(List<String> hideSelectors);

    _FinalStage location(Optional<ScreenshotLocationDto> location);

    _FinalStage location(ScreenshotLocationDto location);

    _FinalStage maskColor(Optional<String> maskColor);

    _FinalStage maskColor(String maskColor);

    /**
     * <p>Cover matching elements with a solid privacy mask</p>
     */
    _FinalStage maskSelectors(Optional<List<String>> maskSelectors);

    _FinalStage maskSelectors(List<String> maskSelectors);

    /**
     * <p>Maximum full-page height. Prevents endless captures on infinite pages.</p>
     */
    _FinalStage maxHeight(Optional<Double> maxHeight);

    _FinalStage maxHeight(Double maxHeight);

    /**
     * <p>Use a transparent background where the page allows it</p>
     */
    _FinalStage omitBackground(Optional<Boolean> omitBackground);

    _FinalStage omitBackground(Boolean omitBackground);

    /**
     * <p>Proxy mode</p>
     */
    _FinalStage proxy(Optional<ScreenshotDtoProxy> proxy);

    _FinalStage proxy(ScreenshotDtoProxy proxy);

    /**
     * <p>JPEG or WebP quality</p>
     */
    _FinalStage quality(Optional<Double> quality);

    _FinalStage quality(Double quality);

    _FinalStage reducedMotion(Optional<Boolean> reducedMotion);

    _FinalStage reducedMotion(Boolean reducedMotion);

    /**
     * <p>Hide common support and chat widgets</p>
     */
    _FinalStage removeChatWidgets(Optional<Boolean> removeChatWidgets);

    _FinalStage removeChatWidgets(Boolean removeChatWidgets);

    /**
     * <p>Accept known consent dialogs, hide remaining cookie banners, and restore page scrolling</p>
     */
    _FinalStage removeCookieBanners(Optional<Boolean> removeCookieBanners);

    _FinalStage removeCookieBanners(Boolean removeCookieBanners);

    /**
     * <p>Remove newsletter gates, modal backdrops, and blocking overlays</p>
     */
    _FinalStage removeOverlays(Optional<Boolean> removeOverlays);

    _FinalStage removeOverlays(Boolean removeOverlays);

    /**
     * <p>Return a CDN URL or an inline data URL</p>
     */
    _FinalStage responseFormat(Optional<ScreenshotDtoResponseFormat> responseFormat);

    _FinalStage responseFormat(ScreenshotDtoResponseFormat responseFormat);

    /**
     * <p>Capture at CSS pixel size or the emulated device pixel ratio</p>
     */
    _FinalStage scale(Optional<ScreenshotDtoScale> scale);

    _FinalStage scale(ScreenshotDtoScale scale);

    /**
     * <p>Pause between lazy-load scroll steps, in milliseconds</p>
     */
    _FinalStage scrollDelay(Optional<Double> scrollDelay);

    _FinalStage scrollDelay(Double scrollDelay);

    /**
     * <p>Scroll through the page first so lazy content is loaded</p>
     */
    _FinalStage scrollPage(Optional<Boolean> scrollPage);

    _FinalStage scrollPage(Boolean scrollPage);

    /**
     * <p>Capture one element instead of the page</p>
     */
    _FinalStage selector(Optional<String> selector);

    _FinalStage selector(String selector);

    /**
     * <p>CSS rules to apply before capture</p>
     */
    _FinalStage styles(Optional<List<String>> styles);

    _FinalStage styles(List<String> styles);

    _FinalStage timeout(Optional<Double> timeout);

    _FinalStage timeout(Double timeout);

    /**
     * <p>Custom viewport. Overrides the named device dimensions.</p>
     */
    _FinalStage viewport(Optional<ScreenshotViewportDto> viewport);

    _FinalStage viewport(ScreenshotViewportDto viewport);

    /**
     * <p>Wait for this CSS selector before capture</p>
     */
    _FinalStage waitForSelector(Optional<String> waitForSelector);

    _FinalStage waitForSelector(String waitForSelector);

    /**
     * <p>Page readiness milestone used before capture</p>
     */
    _FinalStage waitUntil(Optional<ScreenshotDtoWaitUntil> waitUntil);

    _FinalStage waitUntil(ScreenshotDtoWaitUntil waitUntil);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, _FinalStage {
    private String url;

    private Optional<ScreenshotDtoWaitUntil> waitUntil = Optional.empty();

    private Optional<String> waitForSelector = Optional.empty();

    private Optional<ScreenshotViewportDto> viewport = Optional.empty();

    private Optional<Double> timeout = Optional.empty();

    private Optional<List<String>> styles = Optional.empty();

    private Optional<String> selector = Optional.empty();

    private Optional<Boolean> scrollPage = Optional.empty();

    private Optional<Double> scrollDelay = Optional.empty();

    private Optional<ScreenshotDtoScale> scale = Optional.empty();

    private Optional<ScreenshotDtoResponseFormat> responseFormat = Optional.empty();

    private Optional<Boolean> removeOverlays = Optional.empty();

    private Optional<Boolean> removeCookieBanners = Optional.empty();

    private Optional<Boolean> removeChatWidgets = Optional.empty();

    private Optional<Boolean> reducedMotion = Optional.empty();

    private Optional<Double> quality = Optional.empty();

    private Optional<ScreenshotDtoProxy> proxy = Optional.empty();

    private Optional<Boolean> omitBackground = Optional.empty();

    private Optional<Double> maxHeight = Optional.empty();

    private Optional<List<String>> maskSelectors = Optional.empty();

    private Optional<String> maskColor = Optional.empty();

    private Optional<ScreenshotLocationDto> location = Optional.empty();

    private Optional<List<String>> hideSelectors = Optional.empty();

    private Optional<Boolean> hideFixedElements = Optional.empty();

    private Optional<Map<String, Object>> headers = Optional.empty();

    private Optional<ScreenshotDtoFullPageAlgorithm> fullPageAlgorithm = Optional.empty();

    private Optional<Boolean> fullPage = Optional.empty();

    private Optional<ScreenshotDtoFormat> format = Optional.empty();

    private Optional<Boolean> disableAnimations = Optional.empty();

    private Optional<ScreenshotDtoDevice> device = Optional.empty();

    private Optional<Double> delay = Optional.empty();

    private Optional<List<ScreenshotCookieDto>> cookies = Optional.empty();

    private Optional<ScreenshotDtoColorScheme> colorScheme = Optional.empty();

    private Optional<ScreenshotClipDto> clip = Optional.empty();

    private Optional<String> clickSelector = Optional.empty();

    private Optional<Boolean> blockAds = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ScreenshotDto other) {
      blockAds(other.getBlockAds());
      clickSelector(other.getClickSelector());
      clip(other.getClip());
      colorScheme(other.getColorScheme());
      cookies(other.getCookies());
      delay(other.getDelay());
      device(other.getDevice());
      disableAnimations(other.getDisableAnimations());
      format(other.getFormat());
      fullPage(other.getFullPage());
      fullPageAlgorithm(other.getFullPageAlgorithm());
      headers(other.getHeaders());
      hideFixedElements(other.getHideFixedElements());
      hideSelectors(other.getHideSelectors());
      location(other.getLocation());
      maskColor(other.getMaskColor());
      maskSelectors(other.getMaskSelectors());
      maxHeight(other.getMaxHeight());
      omitBackground(other.getOmitBackground());
      proxy(other.getProxy());
      quality(other.getQuality());
      reducedMotion(other.getReducedMotion());
      removeChatWidgets(other.getRemoveChatWidgets());
      removeCookieBanners(other.getRemoveCookieBanners());
      removeOverlays(other.getRemoveOverlays());
      responseFormat(other.getResponseFormat());
      scale(other.getScale());
      scrollDelay(other.getScrollDelay());
      scrollPage(other.getScrollPage());
      selector(other.getSelector());
      styles(other.getStyles());
      timeout(other.getTimeout());
      url(other.getUrl());
      viewport(other.getViewport());
      waitForSelector(other.getWaitForSelector());
      waitUntil(other.getWaitUntil());
      return this;
    }

    /**
     * <p>Public webpage URL to capture</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>Page readiness milestone used before capture</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage waitUntil(ScreenshotDtoWaitUntil waitUntil) {
      this.waitUntil = Optional.ofNullable(waitUntil);
      return this;
    }

    /**
     * <p>Page readiness milestone used before capture</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "waitUntil",
        nulls = Nulls.SKIP
    )
    public _FinalStage waitUntil(Optional<ScreenshotDtoWaitUntil> waitUntil) {
      this.waitUntil = waitUntil;
      return this;
    }

    /**
     * <p>Wait for this CSS selector before capture</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage waitForSelector(String waitForSelector) {
      this.waitForSelector = Optional.ofNullable(waitForSelector);
      return this;
    }

    /**
     * <p>Wait for this CSS selector before capture</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "waitForSelector",
        nulls = Nulls.SKIP
    )
    public _FinalStage waitForSelector(Optional<String> waitForSelector) {
      this.waitForSelector = waitForSelector;
      return this;
    }

    /**
     * <p>Custom viewport. Overrides the named device dimensions.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage viewport(ScreenshotViewportDto viewport) {
      this.viewport = Optional.ofNullable(viewport);
      return this;
    }

    /**
     * <p>Custom viewport. Overrides the named device dimensions.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "viewport",
        nulls = Nulls.SKIP
    )
    public _FinalStage viewport(Optional<ScreenshotViewportDto> viewport) {
      this.viewport = viewport;
      return this;
    }

    @java.lang.Override
    public _FinalStage timeout(Double timeout) {
      this.timeout = Optional.ofNullable(timeout);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "timeout",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeout(Optional<Double> timeout) {
      this.timeout = timeout;
      return this;
    }

    /**
     * <p>CSS rules to apply before capture</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage styles(List<String> styles) {
      this.styles = Optional.ofNullable(styles);
      return this;
    }

    /**
     * <p>CSS rules to apply before capture</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "styles",
        nulls = Nulls.SKIP
    )
    public _FinalStage styles(Optional<List<String>> styles) {
      this.styles = styles;
      return this;
    }

    /**
     * <p>Capture one element instead of the page</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage selector(String selector) {
      this.selector = Optional.ofNullable(selector);
      return this;
    }

    /**
     * <p>Capture one element instead of the page</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "selector",
        nulls = Nulls.SKIP
    )
    public _FinalStage selector(Optional<String> selector) {
      this.selector = selector;
      return this;
    }

    /**
     * <p>Scroll through the page first so lazy content is loaded</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage scrollPage(Boolean scrollPage) {
      this.scrollPage = Optional.ofNullable(scrollPage);
      return this;
    }

    /**
     * <p>Scroll through the page first so lazy content is loaded</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "scrollPage",
        nulls = Nulls.SKIP
    )
    public _FinalStage scrollPage(Optional<Boolean> scrollPage) {
      this.scrollPage = scrollPage;
      return this;
    }

    /**
     * <p>Pause between lazy-load scroll steps, in milliseconds</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage scrollDelay(Double scrollDelay) {
      this.scrollDelay = Optional.ofNullable(scrollDelay);
      return this;
    }

    /**
     * <p>Pause between lazy-load scroll steps, in milliseconds</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "scrollDelay",
        nulls = Nulls.SKIP
    )
    public _FinalStage scrollDelay(Optional<Double> scrollDelay) {
      this.scrollDelay = scrollDelay;
      return this;
    }

    /**
     * <p>Capture at CSS pixel size or the emulated device pixel ratio</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage scale(ScreenshotDtoScale scale) {
      this.scale = Optional.ofNullable(scale);
      return this;
    }

    /**
     * <p>Capture at CSS pixel size or the emulated device pixel ratio</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "scale",
        nulls = Nulls.SKIP
    )
    public _FinalStage scale(Optional<ScreenshotDtoScale> scale) {
      this.scale = scale;
      return this;
    }

    /**
     * <p>Return a CDN URL or an inline data URL</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage responseFormat(ScreenshotDtoResponseFormat responseFormat) {
      this.responseFormat = Optional.ofNullable(responseFormat);
      return this;
    }

    /**
     * <p>Return a CDN URL or an inline data URL</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "responseFormat",
        nulls = Nulls.SKIP
    )
    public _FinalStage responseFormat(Optional<ScreenshotDtoResponseFormat> responseFormat) {
      this.responseFormat = responseFormat;
      return this;
    }

    /**
     * <p>Remove newsletter gates, modal backdrops, and blocking overlays</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage removeOverlays(Boolean removeOverlays) {
      this.removeOverlays = Optional.ofNullable(removeOverlays);
      return this;
    }

    /**
     * <p>Remove newsletter gates, modal backdrops, and blocking overlays</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "removeOverlays",
        nulls = Nulls.SKIP
    )
    public _FinalStage removeOverlays(Optional<Boolean> removeOverlays) {
      this.removeOverlays = removeOverlays;
      return this;
    }

    /**
     * <p>Accept known consent dialogs, hide remaining cookie banners, and restore page scrolling</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage removeCookieBanners(Boolean removeCookieBanners) {
      this.removeCookieBanners = Optional.ofNullable(removeCookieBanners);
      return this;
    }

    /**
     * <p>Accept known consent dialogs, hide remaining cookie banners, and restore page scrolling</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "removeCookieBanners",
        nulls = Nulls.SKIP
    )
    public _FinalStage removeCookieBanners(Optional<Boolean> removeCookieBanners) {
      this.removeCookieBanners = removeCookieBanners;
      return this;
    }

    /**
     * <p>Hide common support and chat widgets</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage removeChatWidgets(Boolean removeChatWidgets) {
      this.removeChatWidgets = Optional.ofNullable(removeChatWidgets);
      return this;
    }

    /**
     * <p>Hide common support and chat widgets</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "removeChatWidgets",
        nulls = Nulls.SKIP
    )
    public _FinalStage removeChatWidgets(Optional<Boolean> removeChatWidgets) {
      this.removeChatWidgets = removeChatWidgets;
      return this;
    }

    @java.lang.Override
    public _FinalStage reducedMotion(Boolean reducedMotion) {
      this.reducedMotion = Optional.ofNullable(reducedMotion);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "reducedMotion",
        nulls = Nulls.SKIP
    )
    public _FinalStage reducedMotion(Optional<Boolean> reducedMotion) {
      this.reducedMotion = reducedMotion;
      return this;
    }

    /**
     * <p>JPEG or WebP quality</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage quality(Double quality) {
      this.quality = Optional.ofNullable(quality);
      return this;
    }

    /**
     * <p>JPEG or WebP quality</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "quality",
        nulls = Nulls.SKIP
    )
    public _FinalStage quality(Optional<Double> quality) {
      this.quality = quality;
      return this;
    }

    /**
     * <p>Proxy mode</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage proxy(ScreenshotDtoProxy proxy) {
      this.proxy = Optional.ofNullable(proxy);
      return this;
    }

    /**
     * <p>Proxy mode</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "proxy",
        nulls = Nulls.SKIP
    )
    public _FinalStage proxy(Optional<ScreenshotDtoProxy> proxy) {
      this.proxy = proxy;
      return this;
    }

    /**
     * <p>Use a transparent background where the page allows it</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage omitBackground(Boolean omitBackground) {
      this.omitBackground = Optional.ofNullable(omitBackground);
      return this;
    }

    /**
     * <p>Use a transparent background where the page allows it</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "omitBackground",
        nulls = Nulls.SKIP
    )
    public _FinalStage omitBackground(Optional<Boolean> omitBackground) {
      this.omitBackground = omitBackground;
      return this;
    }

    /**
     * <p>Maximum full-page height. Prevents endless captures on infinite pages.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage maxHeight(Double maxHeight) {
      this.maxHeight = Optional.ofNullable(maxHeight);
      return this;
    }

    /**
     * <p>Maximum full-page height. Prevents endless captures on infinite pages.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "maxHeight",
        nulls = Nulls.SKIP
    )
    public _FinalStage maxHeight(Optional<Double> maxHeight) {
      this.maxHeight = maxHeight;
      return this;
    }

    /**
     * <p>Cover matching elements with a solid privacy mask</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage maskSelectors(List<String> maskSelectors) {
      this.maskSelectors = Optional.ofNullable(maskSelectors);
      return this;
    }

    /**
     * <p>Cover matching elements with a solid privacy mask</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "maskSelectors",
        nulls = Nulls.SKIP
    )
    public _FinalStage maskSelectors(Optional<List<String>> maskSelectors) {
      this.maskSelectors = maskSelectors;
      return this;
    }

    @java.lang.Override
    public _FinalStage maskColor(String maskColor) {
      this.maskColor = Optional.ofNullable(maskColor);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "maskColor",
        nulls = Nulls.SKIP
    )
    public _FinalStage maskColor(Optional<String> maskColor) {
      this.maskColor = maskColor;
      return this;
    }

    @java.lang.Override
    public _FinalStage location(ScreenshotLocationDto location) {
      this.location = Optional.ofNullable(location);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "location",
        nulls = Nulls.SKIP
    )
    public _FinalStage location(Optional<ScreenshotLocationDto> location) {
      this.location = location;
      return this;
    }

    /**
     * <p>Hide matching elements before capture</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage hideSelectors(List<String> hideSelectors) {
      this.hideSelectors = Optional.ofNullable(hideSelectors);
      return this;
    }

    /**
     * <p>Hide matching elements before capture</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "hideSelectors",
        nulls = Nulls.SKIP
    )
    public _FinalStage hideSelectors(Optional<List<String>> hideSelectors) {
      this.hideSelectors = hideSelectors;
      return this;
    }

    /**
     * <p>Show fixed/sticky UI once instead of repeating it in stitched captures</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage hideFixedElements(Boolean hideFixedElements) {
      this.hideFixedElements = Optional.ofNullable(hideFixedElements);
      return this;
    }

    /**
     * <p>Show fixed/sticky UI once instead of repeating it in stitched captures</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "hideFixedElements",
        nulls = Nulls.SKIP
    )
    public _FinalStage hideFixedElements(Optional<Boolean> hideFixedElements) {
      this.hideFixedElements = hideFixedElements;
      return this;
    }

    /**
     * <p>Headers sent while loading the page</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage headers(Map<String, Object> headers) {
      this.headers = Optional.ofNullable(headers);
      return this;
    }

    /**
     * <p>Headers sent while loading the page</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "headers",
        nulls = Nulls.SKIP
    )
    public _FinalStage headers(Optional<Map<String, Object>> headers) {
      this.headers = headers;
      return this;
    }

    /**
     * <p>auto uses native capture for normal pages and stitched slices for very tall pages</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage fullPageAlgorithm(ScreenshotDtoFullPageAlgorithm fullPageAlgorithm) {
      this.fullPageAlgorithm = Optional.ofNullable(fullPageAlgorithm);
      return this;
    }

    /**
     * <p>auto uses native capture for normal pages and stitched slices for very tall pages</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "fullPageAlgorithm",
        nulls = Nulls.SKIP
    )
    public _FinalStage fullPageAlgorithm(
        Optional<ScreenshotDtoFullPageAlgorithm> fullPageAlgorithm) {
      this.fullPageAlgorithm = fullPageAlgorithm;
      return this;
    }

    /**
     * <p>Capture the complete page instead of only the viewport</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage fullPage(Boolean fullPage) {
      this.fullPage = Optional.ofNullable(fullPage);
      return this;
    }

    /**
     * <p>Capture the complete page instead of only the viewport</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "fullPage",
        nulls = Nulls.SKIP
    )
    public _FinalStage fullPage(Optional<Boolean> fullPage) {
      this.fullPage = fullPage;
      return this;
    }

    @java.lang.Override
    public _FinalStage format(ScreenshotDtoFormat format) {
      this.format = Optional.ofNullable(format);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "format",
        nulls = Nulls.SKIP
    )
    public _FinalStage format(Optional<ScreenshotDtoFormat> format) {
      this.format = format;
      return this;
    }

    @java.lang.Override
    public _FinalStage disableAnimations(Boolean disableAnimations) {
      this.disableAnimations = Optional.ofNullable(disableAnimations);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "disableAnimations",
        nulls = Nulls.SKIP
    )
    public _FinalStage disableAnimations(Optional<Boolean> disableAnimations) {
      this.disableAnimations = disableAnimations;
      return this;
    }

    /**
     * <p>Named viewport preset</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage device(ScreenshotDtoDevice device) {
      this.device = Optional.ofNullable(device);
      return this;
    }

    /**
     * <p>Named viewport preset</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "device",
        nulls = Nulls.SKIP
    )
    public _FinalStage device(Optional<ScreenshotDtoDevice> device) {
      this.device = device;
      return this;
    }

    /**
     * <p>Extra settling time after the page is ready, in milliseconds</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage delay(Double delay) {
      this.delay = Optional.ofNullable(delay);
      return this;
    }

    /**
     * <p>Extra settling time after the page is ready, in milliseconds</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "delay",
        nulls = Nulls.SKIP
    )
    public _FinalStage delay(Optional<Double> delay) {
      this.delay = delay;
      return this;
    }

    /**
     * <p>Cookies to set before loading the page</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage cookies(List<ScreenshotCookieDto> cookies) {
      this.cookies = Optional.ofNullable(cookies);
      return this;
    }

    /**
     * <p>Cookies to set before loading the page</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "cookies",
        nulls = Nulls.SKIP
    )
    public _FinalStage cookies(Optional<List<ScreenshotCookieDto>> cookies) {
      this.cookies = cookies;
      return this;
    }

    @java.lang.Override
    public _FinalStage colorScheme(ScreenshotDtoColorScheme colorScheme) {
      this.colorScheme = Optional.ofNullable(colorScheme);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "colorScheme",
        nulls = Nulls.SKIP
    )
    public _FinalStage colorScheme(Optional<ScreenshotDtoColorScheme> colorScheme) {
      this.colorScheme = colorScheme;
      return this;
    }

    /**
     * <p>Capture an exact pixel rectangle instead of the page</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage clip(ScreenshotClipDto clip) {
      this.clip = Optional.ofNullable(clip);
      return this;
    }

    /**
     * <p>Capture an exact pixel rectangle instead of the page</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "clip",
        nulls = Nulls.SKIP
    )
    public _FinalStage clip(Optional<ScreenshotClipDto> clip) {
      this.clip = clip;
      return this;
    }

    /**
     * <p>Click this CSS selector before capture</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage clickSelector(String clickSelector) {
      this.clickSelector = Optional.ofNullable(clickSelector);
      return this;
    }

    /**
     * <p>Click this CSS selector before capture</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "clickSelector",
        nulls = Nulls.SKIP
    )
    public _FinalStage clickSelector(Optional<String> clickSelector) {
      this.clickSelector = clickSelector;
      return this;
    }

    /**
     * <p>Block common advertising and analytics requests</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage blockAds(Boolean blockAds) {
      this.blockAds = Optional.ofNullable(blockAds);
      return this;
    }

    /**
     * <p>Block common advertising and analytics requests</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "blockAds",
        nulls = Nulls.SKIP
    )
    public _FinalStage blockAds(Optional<Boolean> blockAds) {
      this.blockAds = blockAds;
      return this;
    }

    @java.lang.Override
    public ScreenshotDto build() {
      return new ScreenshotDto(blockAds, clickSelector, clip, colorScheme, cookies, delay, device, disableAnimations, format, fullPage, fullPageAlgorithm, headers, hideFixedElements, hideSelectors, location, maskColor, maskSelectors, maxHeight, omitBackground, proxy, quality, reducedMotion, removeChatWidgets, removeCookieBanners, removeOverlays, responseFormat, scale, scrollDelay, scrollPage, selector, styles, timeout, url, viewport, waitForSelector, waitUntil, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
