/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.requests;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchDto.Builder.class
)
public final class SearchDto {
  private final Optional<List<String>> categories;

  private final Optional<String> country;

  private final Optional<Double> limit;

  private final Optional<String> location;

  private final String query;

  private final Optional<List<String>> sources;

  private final Optional<String> tbs;

  private final Optional<Double> timeout;

  private final Map<String, Object> additionalProperties;

  private SearchDto(Optional<List<String>> categories, Optional<String> country,
      Optional<Double> limit, Optional<String> location, String query,
      Optional<List<String>> sources, Optional<String> tbs, Optional<Double> timeout,
      Map<String, Object> additionalProperties) {
    this.categories = categories;
    this.country = country;
    this.limit = limit;
    this.location = location;
    this.query = query;
    this.sources = sources;
    this.tbs = tbs;
    this.timeout = timeout;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Category filters
   */
  @JsonProperty("categories")
  public Optional<List<String>> getCategories() {
    return categories;
  }

  /**
   * @return Country code
   */
  @JsonProperty("country")
  public Optional<String> getCountry() {
    return country;
  }

  /**
   * @return Maximum number of results
   */
  @JsonProperty("limit")
  public Optional<Double> getLimit() {
    return limit;
  }

  /**
   * @return Location for geo-targeting
   */
  @JsonProperty("location")
  public Optional<String> getLocation() {
    return location;
  }

  /**
   * @return Search query
   */
  @JsonProperty("query")
  public String getQuery() {
    return query;
  }

  /**
   * @return Source types to search
   */
  @JsonProperty("sources")
  public Optional<List<String>> getSources() {
    return sources;
  }

  /**
   * @return Time-based filter (e.g., qdr:d for past day)
   */
  @JsonProperty("tbs")
  public Optional<String> getTbs() {
    return tbs;
  }

  /**
   * @return Timeout for search operation in milliseconds
   */
  @JsonProperty("timeout")
  public Optional<Double> getTimeout() {
    return timeout;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchDto && equalTo((SearchDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchDto other) {
    return categories.equals(other.categories) && country.equals(other.country) && limit.equals(other.limit) && location.equals(other.location) && query.equals(other.query) && sources.equals(other.sources) && tbs.equals(other.tbs) && timeout.equals(other.timeout);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.categories, this.country, this.limit, this.location, this.query, this.sources, this.tbs, this.timeout);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static QueryStage builder() {
    return new Builder();
  }

  public interface QueryStage {
    /**
     * <p>Search query</p>
     */
    _FinalStage query(@NotNull String query);

    Builder from(SearchDto other);
  }

  public interface _FinalStage {
    SearchDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Category filters</p>
     */
    _FinalStage categories(Optional<List<String>> categories);

    _FinalStage categories(List<String> categories);

    /**
     * <p>Country code</p>
     */
    _FinalStage country(Optional<String> country);

    _FinalStage country(String country);

    /**
     * <p>Maximum number of results</p>
     */
    _FinalStage limit(Optional<Double> limit);

    _FinalStage limit(Double limit);

    /**
     * <p>Location for geo-targeting</p>
     */
    _FinalStage location(Optional<String> location);

    _FinalStage location(String location);

    /**
     * <p>Source types to search</p>
     */
    _FinalStage sources(Optional<List<String>> sources);

    _FinalStage sources(List<String> sources);

    /**
     * <p>Time-based filter (e.g., qdr:d for past day)</p>
     */
    _FinalStage tbs(Optional<String> tbs);

    _FinalStage tbs(String tbs);

    /**
     * <p>Timeout for search operation in milliseconds</p>
     */
    _FinalStage timeout(Optional<Double> timeout);

    _FinalStage timeout(Double timeout);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements QueryStage, _FinalStage {
    private String query;

    private Optional<Double> timeout = Optional.empty();

    private Optional<String> tbs = Optional.empty();

    private Optional<List<String>> sources = Optional.empty();

    private Optional<String> location = Optional.empty();

    private Optional<Double> limit = Optional.empty();

    private Optional<String> country = Optional.empty();

    private Optional<List<String>> categories = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SearchDto other) {
      categories(other.getCategories());
      country(other.getCountry());
      limit(other.getLimit());
      location(other.getLocation());
      query(other.getQuery());
      sources(other.getSources());
      tbs(other.getTbs());
      timeout(other.getTimeout());
      return this;
    }

    /**
     * <p>Search query</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("query")
    public _FinalStage query(@NotNull String query) {
      this.query = Objects.requireNonNull(query, "query must not be null");
      return this;
    }

    /**
     * <p>Timeout for search operation in milliseconds</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeout(Double timeout) {
      this.timeout = Optional.ofNullable(timeout);
      return this;
    }

    /**
     * <p>Timeout for search operation in milliseconds</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timeout",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeout(Optional<Double> timeout) {
      this.timeout = timeout;
      return this;
    }

    /**
     * <p>Time-based filter (e.g., qdr:d for past day)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage tbs(String tbs) {
      this.tbs = Optional.ofNullable(tbs);
      return this;
    }

    /**
     * <p>Time-based filter (e.g., qdr:d for past day)</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "tbs",
        nulls = Nulls.SKIP
    )
    public _FinalStage tbs(Optional<String> tbs) {
      this.tbs = tbs;
      return this;
    }

    /**
     * <p>Source types to search</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sources(List<String> sources) {
      this.sources = Optional.ofNullable(sources);
      return this;
    }

    /**
     * <p>Source types to search</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "sources",
        nulls = Nulls.SKIP
    )
    public _FinalStage sources(Optional<List<String>> sources) {
      this.sources = sources;
      return this;
    }

    /**
     * <p>Location for geo-targeting</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage location(String location) {
      this.location = Optional.ofNullable(location);
      return this;
    }

    /**
     * <p>Location for geo-targeting</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "location",
        nulls = Nulls.SKIP
    )
    public _FinalStage location(Optional<String> location) {
      this.location = location;
      return this;
    }

    /**
     * <p>Maximum number of results</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage limit(Double limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    /**
     * <p>Maximum number of results</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public _FinalStage limit(Optional<Double> limit) {
      this.limit = limit;
      return this;
    }

    /**
     * <p>Country code</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage country(String country) {
      this.country = Optional.ofNullable(country);
      return this;
    }

    /**
     * <p>Country code</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "country",
        nulls = Nulls.SKIP
    )
    public _FinalStage country(Optional<String> country) {
      this.country = country;
      return this;
    }

    /**
     * <p>Category filters</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage categories(List<String> categories) {
      this.categories = Optional.ofNullable(categories);
      return this;
    }

    /**
     * <p>Category filters</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "categories",
        nulls = Nulls.SKIP
    )
    public _FinalStage categories(Optional<List<String>> categories) {
      this.categories = categories;
      return this;
    }

    @java.lang.Override
    public SearchDto build() {
      return new SearchDto(categories, country, limit, location, query, sources, tbs, timeout, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
