/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.webhooks.requests;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TestWebhookDto.Builder.class
)
public final class TestWebhookDto {
  private final String event;

  private final Optional<Map<String, Object>> payload;

  private final Map<String, Object> additionalProperties;

  private TestWebhookDto(String event, Optional<Map<String, Object>> payload,
      Map<String, Object> additionalProperties) {
    this.event = event;
    this.payload = payload;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Event type to test
   */
  @JsonProperty("event")
  public String getEvent() {
    return event;
  }

  /**
   * @return Optional custom payload for testing
   */
  @JsonProperty("payload")
  public Optional<Map<String, Object>> getPayload() {
    return payload;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TestWebhookDto && equalTo((TestWebhookDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TestWebhookDto other) {
    return event.equals(other.event) && payload.equals(other.payload);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.event, this.payload);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EventStage builder() {
    return new Builder();
  }

  public interface EventStage {
    /**
     * <p>Event type to test</p>
     */
    _FinalStage event(@NotNull String event);

    Builder from(TestWebhookDto other);
  }

  public interface _FinalStage {
    TestWebhookDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Optional custom payload for testing</p>
     */
    _FinalStage payload(Optional<Map<String, Object>> payload);

    _FinalStage payload(Map<String, Object> payload);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EventStage, _FinalStage {
    private String event;

    private Optional<Map<String, Object>> payload = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TestWebhookDto other) {
      event(other.getEvent());
      payload(other.getPayload());
      return this;
    }

    /**
     * <p>Event type to test</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("event")
    public _FinalStage event(@NotNull String event) {
      this.event = Objects.requireNonNull(event, "event must not be null");
      return this;
    }

    /**
     * <p>Optional custom payload for testing</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage payload(Map<String, Object> payload) {
      this.payload = Optional.ofNullable(payload);
      return this;
    }

    /**
     * <p>Optional custom payload for testing</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "payload",
        nulls = Nulls.SKIP
    )
    public _FinalStage payload(Optional<Map<String, Object>> payload) {
      this.payload = payload;
      return this;
    }

    @java.lang.Override
    public TestWebhookDto build() {
      return new TestWebhookDto(event, payload, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
