/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AccountResponseDataQueue.Builder.class
)
public final class AccountResponseDataQueue {
  private final int active;

  private final int waiting;

  private final Map<String, Object> additionalProperties;

  private AccountResponseDataQueue(int active, int waiting,
      Map<String, Object> additionalProperties) {
    this.active = active;
    this.waiting = waiting;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("active")
  public int getActive() {
    return active;
  }

  @JsonProperty("waiting")
  public int getWaiting() {
    return waiting;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AccountResponseDataQueue && equalTo((AccountResponseDataQueue) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AccountResponseDataQueue other) {
    return active == other.active && waiting == other.waiting;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.active, this.waiting);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ActiveStage builder() {
    return new Builder();
  }

  public interface ActiveStage {
    WaitingStage active(int active);

    Builder from(AccountResponseDataQueue other);
  }

  public interface WaitingStage {
    _FinalStage waiting(int waiting);
  }

  public interface _FinalStage {
    AccountResponseDataQueue build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ActiveStage, WaitingStage, _FinalStage {
    private int active;

    private int waiting;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AccountResponseDataQueue other) {
      active(other.getActive());
      waiting(other.getWaiting());
      return this;
    }

    @java.lang.Override
    @JsonSetter("active")
    public WaitingStage active(int active) {
      this.active = active;
      return this;
    }

    @java.lang.Override
    @JsonSetter("waiting")
    public _FinalStage waiting(int waiting) {
      this.waiting = waiting;
      return this;
    }

    @java.lang.Override
    public AccountResponseDataQueue build() {
      return new AccountResponseDataQueue(active, waiting, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
