/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ActionDtoDirection {
  public static final ActionDtoDirection DOWN = new ActionDtoDirection(Value.DOWN, "down");

  public static final ActionDtoDirection UP = new ActionDtoDirection(Value.UP, "up");

  private final Value value;

  private final String string;

  ActionDtoDirection(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ActionDtoDirection && this.string.equals(((ActionDtoDirection) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DOWN:
        return visitor.visitDown();
      case UP:
        return visitor.visitUp();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ActionDtoDirection valueOf(String value) {
    switch (value) {
      case "down":
        return DOWN;
      case "up":
        return UP;
      default:
        return new ActionDtoDirection(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    UP,

    DOWN,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitUp();

    T visitDown();

    T visitUnknown(String unknownType);
  }
}
