/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ActionDto.Builder.class
)
public final class ActionDto {
  private final Optional<Double> amount;

  private final Optional<ActionDtoDirection> direction;

  private final Optional<String> key;

  private final Optional<Double> milliseconds;

  private final Optional<String> selector;

  private final Optional<String> text;

  private final ActionDtoType type;

  private final Map<String, Object> additionalProperties;

  private ActionDto(Optional<Double> amount, Optional<ActionDtoDirection> direction,
      Optional<String> key, Optional<Double> milliseconds, Optional<String> selector,
      Optional<String> text, ActionDtoType type, Map<String, Object> additionalProperties) {
    this.amount = amount;
    this.direction = direction;
    this.key = key;
    this.milliseconds = milliseconds;
    this.selector = selector;
    this.text = text;
    this.type = type;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("amount")
  public Optional<Double> getAmount() {
    return amount;
  }

  @JsonProperty("direction")
  public Optional<ActionDtoDirection> getDirection() {
    return direction;
  }

  @JsonProperty("key")
  public Optional<String> getKey() {
    return key;
  }

  @JsonProperty("milliseconds")
  public Optional<Double> getMilliseconds() {
    return milliseconds;
  }

  @JsonProperty("selector")
  public Optional<String> getSelector() {
    return selector;
  }

  @JsonProperty("text")
  public Optional<String> getText() {
    return text;
  }

  @JsonProperty("type")
  public ActionDtoType getType() {
    return type;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ActionDto && equalTo((ActionDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ActionDto other) {
    return amount.equals(other.amount) && direction.equals(other.direction) && key.equals(other.key) && milliseconds.equals(other.milliseconds) && selector.equals(other.selector) && text.equals(other.text) && type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.amount, this.direction, this.key, this.milliseconds, this.selector, this.text, this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    _FinalStage type(@NotNull ActionDtoType type);

    Builder from(ActionDto other);
  }

  public interface _FinalStage {
    ActionDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage amount(Optional<Double> amount);

    _FinalStage amount(Double amount);

    _FinalStage direction(Optional<ActionDtoDirection> direction);

    _FinalStage direction(ActionDtoDirection direction);

    _FinalStage key(Optional<String> key);

    _FinalStage key(String key);

    _FinalStage milliseconds(Optional<Double> milliseconds);

    _FinalStage milliseconds(Double milliseconds);

    _FinalStage selector(Optional<String> selector);

    _FinalStage selector(String selector);

    _FinalStage text(Optional<String> text);

    _FinalStage text(String text);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, _FinalStage {
    private ActionDtoType type;

    private Optional<String> text = Optional.empty();

    private Optional<String> selector = Optional.empty();

    private Optional<Double> milliseconds = Optional.empty();

    private Optional<String> key = Optional.empty();

    private Optional<ActionDtoDirection> direction = Optional.empty();

    private Optional<Double> amount = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ActionDto other) {
      amount(other.getAmount());
      direction(other.getDirection());
      key(other.getKey());
      milliseconds(other.getMilliseconds());
      selector(other.getSelector());
      text(other.getText());
      type(other.getType());
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull ActionDtoType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage text(String text) {
      this.text = Optional.ofNullable(text);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "text",
        nulls = Nulls.SKIP
    )
    public _FinalStage text(Optional<String> text) {
      this.text = text;
      return this;
    }

    @java.lang.Override
    public _FinalStage selector(String selector) {
      this.selector = Optional.ofNullable(selector);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "selector",
        nulls = Nulls.SKIP
    )
    public _FinalStage selector(Optional<String> selector) {
      this.selector = selector;
      return this;
    }

    @java.lang.Override
    public _FinalStage milliseconds(Double milliseconds) {
      this.milliseconds = Optional.ofNullable(milliseconds);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "milliseconds",
        nulls = Nulls.SKIP
    )
    public _FinalStage milliseconds(Optional<Double> milliseconds) {
      this.milliseconds = milliseconds;
      return this;
    }

    @java.lang.Override
    public _FinalStage key(String key) {
      this.key = Optional.ofNullable(key);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "key",
        nulls = Nulls.SKIP
    )
    public _FinalStage key(Optional<String> key) {
      this.key = key;
      return this;
    }

    @java.lang.Override
    public _FinalStage direction(ActionDtoDirection direction) {
      this.direction = Optional.ofNullable(direction);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "direction",
        nulls = Nulls.SKIP
    )
    public _FinalStage direction(Optional<ActionDtoDirection> direction) {
      this.direction = direction;
      return this;
    }

    @java.lang.Override
    public _FinalStage amount(Double amount) {
      this.amount = Optional.ofNullable(amount);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "amount",
        nulls = Nulls.SKIP
    )
    public _FinalStage amount(Optional<Double> amount) {
      this.amount = amount;
      return this;
    }

    @java.lang.Override
    public ActionDto build() {
      return new ActionDto(amount, direction, key, milliseconds, selector, text, type, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
