/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class AgentConfigDtoMode {
  public static final AgentConfigDtoMode DEFAULT = new AgentConfigDtoMode(Value.DEFAULT, "default");

  public static final AgentConfigDtoMode SMART = new AgentConfigDtoMode(Value.SMART, "smart");

  private final Value value;

  private final String string;

  AgentConfigDtoMode(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof AgentConfigDtoMode && this.string.equals(((AgentConfigDtoMode) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case DEFAULT:
        return visitor.visitDefault();
      case SMART:
        return visitor.visitSmart();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static AgentConfigDtoMode valueOf(String value) {
    switch (value) {
      case "default":
        return DEFAULT;
      case "smart":
        return SMART;
      default:
        return new AgentConfigDtoMode(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DEFAULT,

    SMART,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDefault();

    T visitSmart();

    T visitUnknown(String unknownType);
  }
}
