/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandDesignSystemTypographyFontFamilies.Builder.class
)
public final class BrandDesignSystemTypographyFontFamilies {
  private final Optional<String> heading;

  private final Optional<String> primary;

  private final Map<String, Object> additionalProperties;

  private BrandDesignSystemTypographyFontFamilies(Optional<String> heading,
      Optional<String> primary, Map<String, Object> additionalProperties) {
    this.heading = heading;
    this.primary = primary;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("heading")
  public Optional<String> getHeading() {
    return heading;
  }

  @JsonProperty("primary")
  public Optional<String> getPrimary() {
    return primary;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandDesignSystemTypographyFontFamilies && equalTo((BrandDesignSystemTypographyFontFamilies) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandDesignSystemTypographyFontFamilies other) {
    return heading.equals(other.heading) && primary.equals(other.primary);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.heading, this.primary);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> heading = Optional.empty();

    private Optional<String> primary = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(BrandDesignSystemTypographyFontFamilies other) {
      heading(other.getHeading());
      primary(other.getPrimary());
      return this;
    }

    @JsonSetter(
        value = "heading",
        nulls = Nulls.SKIP
    )
    public Builder heading(Optional<String> heading) {
      this.heading = heading;
      return this;
    }

    public Builder heading(String heading) {
      this.heading = Optional.ofNullable(heading);
      return this;
    }

    @JsonSetter(
        value = "primary",
        nulls = Nulls.SKIP
    )
    public Builder primary(Optional<String> primary) {
      this.primary = primary;
      return this;
    }

    public Builder primary(String primary) {
      this.primary = Optional.ofNullable(primary);
      return this;
    }

    public BrandDesignSystemTypographyFontFamilies build() {
      return new BrandDesignSystemTypographyFontFamilies(heading, primary, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
