/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandResponseDataMeta.Builder.class
)
public final class BrandResponseDataMeta {
  private final boolean cached;

  private final int creditsUsed;

  private final OffsetDateTime fetchedAt;

  private final String sourceUrl;

  private final Map<String, Object> additionalProperties;

  private BrandResponseDataMeta(boolean cached, int creditsUsed, OffsetDateTime fetchedAt,
      String sourceUrl, Map<String, Object> additionalProperties) {
    this.cached = cached;
    this.creditsUsed = creditsUsed;
    this.fetchedAt = fetchedAt;
    this.sourceUrl = sourceUrl;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("cached")
  public boolean getCached() {
    return cached;
  }

  @JsonProperty("creditsUsed")
  public int getCreditsUsed() {
    return creditsUsed;
  }

  @JsonProperty("fetchedAt")
  public OffsetDateTime getFetchedAt() {
    return fetchedAt;
  }

  @JsonProperty("sourceUrl")
  public String getSourceUrl() {
    return sourceUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandResponseDataMeta && equalTo((BrandResponseDataMeta) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandResponseDataMeta other) {
    return cached == other.cached && creditsUsed == other.creditsUsed && fetchedAt.equals(other.fetchedAt) && sourceUrl.equals(other.sourceUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.cached, this.creditsUsed, this.fetchedAt, this.sourceUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CachedStage builder() {
    return new Builder();
  }

  public interface CachedStage {
    CreditsUsedStage cached(boolean cached);

    Builder from(BrandResponseDataMeta other);
  }

  public interface CreditsUsedStage {
    FetchedAtStage creditsUsed(int creditsUsed);
  }

  public interface FetchedAtStage {
    SourceUrlStage fetchedAt(@NotNull OffsetDateTime fetchedAt);
  }

  public interface SourceUrlStage {
    _FinalStage sourceUrl(@NotNull String sourceUrl);
  }

  public interface _FinalStage {
    BrandResponseDataMeta build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CachedStage, CreditsUsedStage, FetchedAtStage, SourceUrlStage, _FinalStage {
    private boolean cached;

    private int creditsUsed;

    private OffsetDateTime fetchedAt;

    private String sourceUrl;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandResponseDataMeta other) {
      cached(other.getCached());
      creditsUsed(other.getCreditsUsed());
      fetchedAt(other.getFetchedAt());
      sourceUrl(other.getSourceUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("cached")
    public CreditsUsedStage cached(boolean cached) {
      this.cached = cached;
      return this;
    }

    @java.lang.Override
    @JsonSetter("creditsUsed")
    public FetchedAtStage creditsUsed(int creditsUsed) {
      this.creditsUsed = creditsUsed;
      return this;
    }

    @java.lang.Override
    @JsonSetter("fetchedAt")
    public SourceUrlStage fetchedAt(@NotNull OffsetDateTime fetchedAt) {
      this.fetchedAt = Objects.requireNonNull(fetchedAt, "fetchedAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("sourceUrl")
    public _FinalStage sourceUrl(@NotNull String sourceUrl) {
      this.sourceUrl = Objects.requireNonNull(sourceUrl, "sourceUrl must not be null");
      return this;
    }

    @java.lang.Override
    public BrandResponseDataMeta build() {
      return new BrandResponseDataMeta(cached, creditsUsed, fetchedAt, sourceUrl, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
