/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandProfile.Builder.class
)
public final class BrandProfile {
  private final List<BrandProfileColorsItem> colors;

  private final Optional<String> description;

  private final String domain;

  private final List<BrandProfileFontsItem> fonts;

  private final List<BrandAsset> images;

  private final Optional<String> language;

  private final List<BrandAsset> logos;

  private final String name;

  private final List<BrandProfileSocialsItem> socials;

  private final Optional<String> tagline;

  private final Map<String, Object> additionalProperties;

  private BrandProfile(List<BrandProfileColorsItem> colors, Optional<String> description,
      String domain, List<BrandProfileFontsItem> fonts, List<BrandAsset> images,
      Optional<String> language, List<BrandAsset> logos, String name,
      List<BrandProfileSocialsItem> socials, Optional<String> tagline,
      Map<String, Object> additionalProperties) {
    this.colors = colors;
    this.description = description;
    this.domain = domain;
    this.fonts = fonts;
    this.images = images;
    this.language = language;
    this.logos = logos;
    this.name = name;
    this.socials = socials;
    this.tagline = tagline;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("colors")
  public List<BrandProfileColorsItem> getColors() {
    return colors;
  }

  @JsonProperty("description")
  public Optional<String> getDescription() {
    return description;
  }

  @JsonProperty("domain")
  public String getDomain() {
    return domain;
  }

  @JsonProperty("fonts")
  public List<BrandProfileFontsItem> getFonts() {
    return fonts;
  }

  @JsonProperty("images")
  public List<BrandAsset> getImages() {
    return images;
  }

  @JsonProperty("language")
  public Optional<String> getLanguage() {
    return language;
  }

  @JsonProperty("logos")
  public List<BrandAsset> getLogos() {
    return logos;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("socials")
  public List<BrandProfileSocialsItem> getSocials() {
    return socials;
  }

  @JsonProperty("tagline")
  public Optional<String> getTagline() {
    return tagline;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandProfile && equalTo((BrandProfile) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandProfile other) {
    return colors.equals(other.colors) && description.equals(other.description) && domain.equals(other.domain) && fonts.equals(other.fonts) && images.equals(other.images) && language.equals(other.language) && logos.equals(other.logos) && name.equals(other.name) && socials.equals(other.socials) && tagline.equals(other.tagline);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.colors, this.description, this.domain, this.fonts, this.images, this.language, this.logos, this.name, this.socials, this.tagline);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DomainStage builder() {
    return new Builder();
  }

  public interface DomainStage {
    NameStage domain(@NotNull String domain);

    Builder from(BrandProfile other);
  }

  public interface NameStage {
    _FinalStage name(@NotNull String name);
  }

  public interface _FinalStage {
    BrandProfile build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage colors(List<BrandProfileColorsItem> colors);

    _FinalStage addColors(BrandProfileColorsItem colors);

    _FinalStage addAllColors(List<BrandProfileColorsItem> colors);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage fonts(List<BrandProfileFontsItem> fonts);

    _FinalStage addFonts(BrandProfileFontsItem fonts);

    _FinalStage addAllFonts(List<BrandProfileFontsItem> fonts);

    _FinalStage images(List<BrandAsset> images);

    _FinalStage addImages(BrandAsset images);

    _FinalStage addAllImages(List<BrandAsset> images);

    _FinalStage language(Optional<String> language);

    _FinalStage language(String language);

    _FinalStage logos(List<BrandAsset> logos);

    _FinalStage addLogos(BrandAsset logos);

    _FinalStage addAllLogos(List<BrandAsset> logos);

    _FinalStage socials(List<BrandProfileSocialsItem> socials);

    _FinalStage addSocials(BrandProfileSocialsItem socials);

    _FinalStage addAllSocials(List<BrandProfileSocialsItem> socials);

    _FinalStage tagline(Optional<String> tagline);

    _FinalStage tagline(String tagline);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DomainStage, NameStage, _FinalStage {
    private String domain;

    private String name;

    private Optional<String> tagline = Optional.empty();

    private List<BrandProfileSocialsItem> socials = new ArrayList<>();

    private List<BrandAsset> logos = new ArrayList<>();

    private Optional<String> language = Optional.empty();

    private List<BrandAsset> images = new ArrayList<>();

    private List<BrandProfileFontsItem> fonts = new ArrayList<>();

    private Optional<String> description = Optional.empty();

    private List<BrandProfileColorsItem> colors = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandProfile other) {
      colors(other.getColors());
      description(other.getDescription());
      domain(other.getDomain());
      fonts(other.getFonts());
      images(other.getImages());
      language(other.getLanguage());
      logos(other.getLogos());
      name(other.getName());
      socials(other.getSocials());
      tagline(other.getTagline());
      return this;
    }

    @java.lang.Override
    @JsonSetter("domain")
    public NameStage domain(@NotNull String domain) {
      this.domain = Objects.requireNonNull(domain, "domain must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public _FinalStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage tagline(String tagline) {
      this.tagline = Optional.ofNullable(tagline);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "tagline",
        nulls = Nulls.SKIP
    )
    public _FinalStage tagline(Optional<String> tagline) {
      this.tagline = tagline;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllSocials(List<BrandProfileSocialsItem> socials) {
      if (socials != null) {
        this.socials.addAll(socials);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addSocials(BrandProfileSocialsItem socials) {
      this.socials.add(socials);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "socials",
        nulls = Nulls.SKIP
    )
    public _FinalStage socials(List<BrandProfileSocialsItem> socials) {
      this.socials.clear();
      if (socials != null) {
        this.socials.addAll(socials);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllLogos(List<BrandAsset> logos) {
      if (logos != null) {
        this.logos.addAll(logos);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addLogos(BrandAsset logos) {
      this.logos.add(logos);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "logos",
        nulls = Nulls.SKIP
    )
    public _FinalStage logos(List<BrandAsset> logos) {
      this.logos.clear();
      if (logos != null) {
        this.logos.addAll(logos);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage language(String language) {
      this.language = Optional.ofNullable(language);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "language",
        nulls = Nulls.SKIP
    )
    public _FinalStage language(Optional<String> language) {
      this.language = language;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllImages(List<BrandAsset> images) {
      if (images != null) {
        this.images.addAll(images);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addImages(BrandAsset images) {
      this.images.add(images);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "images",
        nulls = Nulls.SKIP
    )
    public _FinalStage images(List<BrandAsset> images) {
      this.images.clear();
      if (images != null) {
        this.images.addAll(images);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllFonts(List<BrandProfileFontsItem> fonts) {
      if (fonts != null) {
        this.fonts.addAll(fonts);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addFonts(BrandProfileFontsItem fonts) {
      this.fonts.add(fonts);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "fonts",
        nulls = Nulls.SKIP
    )
    public _FinalStage fonts(List<BrandProfileFontsItem> fonts) {
      this.fonts.clear();
      if (fonts != null) {
        this.fonts.addAll(fonts);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllColors(List<BrandProfileColorsItem> colors) {
      if (colors != null) {
        this.colors.addAll(colors);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addColors(BrandProfileColorsItem colors) {
      this.colors.add(colors);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "colors",
        nulls = Nulls.SKIP
    )
    public _FinalStage colors(List<BrandProfileColorsItem> colors) {
      this.colors.clear();
      if (colors != null) {
        this.colors.addAll(colors);
      }
      return this;
    }

    @java.lang.Override
    public BrandProfile build() {
      return new BrandProfile(colors, description, domain, fonts, images, language, logos, name, socials, tagline, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
