/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandDesignSystemTypography.Builder.class
)
public final class BrandDesignSystemTypography {
  private final BrandDesignSystemTypographyFontFamilies fontFamilies;

  private final BrandDesignSystemTypographyFontSizes fontSizes;

  private final BrandDesignSystemTypographyFontStacks fontStacks;

  private final Map<String, Object> additionalProperties;

  private BrandDesignSystemTypography(BrandDesignSystemTypographyFontFamilies fontFamilies,
      BrandDesignSystemTypographyFontSizes fontSizes,
      BrandDesignSystemTypographyFontStacks fontStacks, Map<String, Object> additionalProperties) {
    this.fontFamilies = fontFamilies;
    this.fontSizes = fontSizes;
    this.fontStacks = fontStacks;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("fontFamilies")
  public BrandDesignSystemTypographyFontFamilies getFontFamilies() {
    return fontFamilies;
  }

  @JsonProperty("fontSizes")
  public BrandDesignSystemTypographyFontSizes getFontSizes() {
    return fontSizes;
  }

  @JsonProperty("fontStacks")
  public BrandDesignSystemTypographyFontStacks getFontStacks() {
    return fontStacks;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandDesignSystemTypography && equalTo((BrandDesignSystemTypography) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandDesignSystemTypography other) {
    return fontFamilies.equals(other.fontFamilies) && fontSizes.equals(other.fontSizes) && fontStacks.equals(other.fontStacks);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.fontFamilies, this.fontSizes, this.fontStacks);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FontFamiliesStage builder() {
    return new Builder();
  }

  public interface FontFamiliesStage {
    FontSizesStage fontFamilies(@NotNull BrandDesignSystemTypographyFontFamilies fontFamilies);

    Builder from(BrandDesignSystemTypography other);
  }

  public interface FontSizesStage {
    FontStacksStage fontSizes(@NotNull BrandDesignSystemTypographyFontSizes fontSizes);
  }

  public interface FontStacksStage {
    _FinalStage fontStacks(@NotNull BrandDesignSystemTypographyFontStacks fontStacks);
  }

  public interface _FinalStage {
    BrandDesignSystemTypography build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FontFamiliesStage, FontSizesStage, FontStacksStage, _FinalStage {
    private BrandDesignSystemTypographyFontFamilies fontFamilies;

    private BrandDesignSystemTypographyFontSizes fontSizes;

    private BrandDesignSystemTypographyFontStacks fontStacks;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandDesignSystemTypography other) {
      fontFamilies(other.getFontFamilies());
      fontSizes(other.getFontSizes());
      fontStacks(other.getFontStacks());
      return this;
    }

    @java.lang.Override
    @JsonSetter("fontFamilies")
    public FontSizesStage fontFamilies(
        @NotNull BrandDesignSystemTypographyFontFamilies fontFamilies) {
      this.fontFamilies = Objects.requireNonNull(fontFamilies, "fontFamilies must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("fontSizes")
    public FontStacksStage fontSizes(@NotNull BrandDesignSystemTypographyFontSizes fontSizes) {
      this.fontSizes = Objects.requireNonNull(fontSizes, "fontSizes must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("fontStacks")
    public _FinalStage fontStacks(@NotNull BrandDesignSystemTypographyFontStacks fontStacks) {
      this.fontStacks = Objects.requireNonNull(fontStacks, "fontStacks must not be null");
      return this;
    }

    @java.lang.Override
    public BrandDesignSystemTypography build() {
      return new BrandDesignSystemTypography(fontFamilies, fontSizes, fontStacks, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
