/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandResponseData.Builder.class
)
public final class BrandResponseData {
  private final BrandProfile brand;

  private final BrandResponseDataMeta meta;

  private final Map<String, Object> additionalProperties;

  private BrandResponseData(BrandProfile brand, BrandResponseDataMeta meta,
      Map<String, Object> additionalProperties) {
    this.brand = brand;
    this.meta = meta;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("brand")
  public BrandProfile getBrand() {
    return brand;
  }

  @JsonProperty("meta")
  public BrandResponseDataMeta getMeta() {
    return meta;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandResponseData && equalTo((BrandResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandResponseData other) {
    return brand.equals(other.brand) && meta.equals(other.meta);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.brand, this.meta);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BrandStage builder() {
    return new Builder();
  }

  public interface BrandStage {
    MetaStage brand(@NotNull BrandProfile brand);

    Builder from(BrandResponseData other);
  }

  public interface MetaStage {
    _FinalStage meta(@NotNull BrandResponseDataMeta meta);
  }

  public interface _FinalStage {
    BrandResponseData build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements BrandStage, MetaStage, _FinalStage {
    private BrandProfile brand;

    private BrandResponseDataMeta meta;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandResponseData other) {
      brand(other.getBrand());
      meta(other.getMeta());
      return this;
    }

    @java.lang.Override
    @JsonSetter("brand")
    public MetaStage brand(@NotNull BrandProfile brand) {
      this.brand = Objects.requireNonNull(brand, "brand must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("meta")
    public _FinalStage meta(@NotNull BrandResponseDataMeta meta) {
      this.meta = Objects.requireNonNull(meta, "meta must not be null");
      return this;
    }

    @java.lang.Override
    public BrandResponseData build() {
      return new BrandResponseData(brand, meta, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
