/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandProfileColorsItem.Builder.class
)
public final class BrandProfileColorsItem {
  private final String hex;

  private final Optional<String> name;

  private final Map<String, Object> additionalProperties;

  private BrandProfileColorsItem(String hex, Optional<String> name,
      Map<String, Object> additionalProperties) {
    this.hex = hex;
    this.name = name;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("hex")
  public String getHex() {
    return hex;
  }

  @JsonProperty("name")
  public Optional<String> getName() {
    return name;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandProfileColorsItem && equalTo((BrandProfileColorsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandProfileColorsItem other) {
    return hex.equals(other.hex) && name.equals(other.name);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.hex, this.name);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static HexStage builder() {
    return new Builder();
  }

  public interface HexStage {
    _FinalStage hex(@NotNull String hex);

    Builder from(BrandProfileColorsItem other);
  }

  public interface _FinalStage {
    BrandProfileColorsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage name(Optional<String> name);

    _FinalStage name(String name);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements HexStage, _FinalStage {
    private String hex;

    private Optional<String> name = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandProfileColorsItem other) {
      hex(other.getHex());
      name(other.getName());
      return this;
    }

    @java.lang.Override
    @JsonSetter("hex")
    public _FinalStage hex(@NotNull String hex) {
      this.hex = Objects.requireNonNull(hex, "hex must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage name(String name) {
      this.name = Optional.ofNullable(name);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "name",
        nulls = Nulls.SKIP
    )
    public _FinalStage name(Optional<String> name) {
      this.name = name;
      return this;
    }

    @java.lang.Override
    public BrandProfileColorsItem build() {
      return new BrandProfileColorsItem(hex, name, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
