/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandDesignSystemSpacing.Builder.class
)
public final class BrandDesignSystemSpacing {
  private final double baseUnit;

  private final Optional<String> borderRadius;

  private final Map<String, Object> additionalProperties;

  private BrandDesignSystemSpacing(double baseUnit, Optional<String> borderRadius,
      Map<String, Object> additionalProperties) {
    this.baseUnit = baseUnit;
    this.borderRadius = borderRadius;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("baseUnit")
  public double getBaseUnit() {
    return baseUnit;
  }

  @JsonProperty("borderRadius")
  public Optional<String> getBorderRadius() {
    return borderRadius;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandDesignSystemSpacing && equalTo((BrandDesignSystemSpacing) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandDesignSystemSpacing other) {
    return baseUnit == other.baseUnit && borderRadius.equals(other.borderRadius);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.baseUnit, this.borderRadius);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static BaseUnitStage builder() {
    return new Builder();
  }

  public interface BaseUnitStage {
    _FinalStage baseUnit(double baseUnit);

    Builder from(BrandDesignSystemSpacing other);
  }

  public interface _FinalStage {
    BrandDesignSystemSpacing build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage borderRadius(Optional<String> borderRadius);

    _FinalStage borderRadius(String borderRadius);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements BaseUnitStage, _FinalStage {
    private double baseUnit;

    private Optional<String> borderRadius = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandDesignSystemSpacing other) {
      baseUnit(other.getBaseUnit());
      borderRadius(other.getBorderRadius());
      return this;
    }

    @java.lang.Override
    @JsonSetter("baseUnit")
    public _FinalStage baseUnit(double baseUnit) {
      this.baseUnit = baseUnit;
      return this;
    }

    @java.lang.Override
    public _FinalStage borderRadius(String borderRadius) {
      this.borderRadius = Optional.ofNullable(borderRadius);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "borderRadius",
        nulls = Nulls.SKIP
    )
    public _FinalStage borderRadius(Optional<String> borderRadius) {
      this.borderRadius = borderRadius;
      return this;
    }

    @java.lang.Override
    public BrandDesignSystemSpacing build() {
      return new BrandDesignSystemSpacing(baseUnit, borderRadius, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
