/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandAsset.Builder.class
)
public final class BrandAsset {
  private final Optional<Integer> height;

  private final Optional<String> theme;

  private final String type;

  private final String url;

  private final Optional<Integer> width;

  private final Map<String, Object> additionalProperties;

  private BrandAsset(Optional<Integer> height, Optional<String> theme, String type, String url,
      Optional<Integer> width, Map<String, Object> additionalProperties) {
    this.height = height;
    this.theme = theme;
    this.type = type;
    this.url = url;
    this.width = width;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("height")
  public Optional<Integer> getHeight() {
    return height;
  }

  @JsonProperty("theme")
  public Optional<String> getTheme() {
    return theme;
  }

  @JsonProperty("type")
  public String getType() {
    return type;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @JsonProperty("width")
  public Optional<Integer> getWidth() {
    return width;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandAsset && equalTo((BrandAsset) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandAsset other) {
    return height.equals(other.height) && theme.equals(other.theme) && type.equals(other.type) && url.equals(other.url) && width.equals(other.width);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.height, this.theme, this.type, this.url, this.width);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    UrlStage type(@NotNull String type);

    Builder from(BrandAsset other);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    BrandAsset build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage height(Optional<Integer> height);

    _FinalStage height(Integer height);

    _FinalStage theme(Optional<String> theme);

    _FinalStage theme(String theme);

    _FinalStage width(Optional<Integer> width);

    _FinalStage width(Integer width);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, UrlStage, _FinalStage {
    private String type;

    private String url;

    private Optional<Integer> width = Optional.empty();

    private Optional<String> theme = Optional.empty();

    private Optional<Integer> height = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandAsset other) {
      height(other.getHeight());
      theme(other.getTheme());
      type(other.getType());
      url(other.getUrl());
      width(other.getWidth());
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public UrlStage type(@NotNull String type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage width(Integer width) {
      this.width = Optional.ofNullable(width);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "width",
        nulls = Nulls.SKIP
    )
    public _FinalStage width(Optional<Integer> width) {
      this.width = width;
      return this;
    }

    @java.lang.Override
    public _FinalStage theme(String theme) {
      this.theme = Optional.ofNullable(theme);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "theme",
        nulls = Nulls.SKIP
    )
    public _FinalStage theme(Optional<String> theme) {
      this.theme = theme;
      return this;
    }

    @java.lang.Override
    public _FinalStage height(Integer height) {
      this.height = Optional.ofNullable(height);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "height",
        nulls = Nulls.SKIP
    )
    public _FinalStage height(Optional<Integer> height) {
      this.height = height;
      return this;
    }

    @java.lang.Override
    public BrandAsset build() {
      return new BrandAsset(height, theme, type, url, width, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
