/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandDesignSystemImages.Builder.class
)
public final class BrandDesignSystemImages {
  private final Optional<String> favicon;

  private final Optional<String> logo;

  private final Optional<String> ogImage;

  private final Map<String, Object> additionalProperties;

  private BrandDesignSystemImages(Optional<String> favicon, Optional<String> logo,
      Optional<String> ogImage, Map<String, Object> additionalProperties) {
    this.favicon = favicon;
    this.logo = logo;
    this.ogImage = ogImage;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("favicon")
  public Optional<String> getFavicon() {
    return favicon;
  }

  @JsonProperty("logo")
  public Optional<String> getLogo() {
    return logo;
  }

  @JsonProperty("ogImage")
  public Optional<String> getOgImage() {
    return ogImage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandDesignSystemImages && equalTo((BrandDesignSystemImages) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandDesignSystemImages other) {
    return favicon.equals(other.favicon) && logo.equals(other.logo) && ogImage.equals(other.ogImage);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.favicon, this.logo, this.ogImage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> favicon = Optional.empty();

    private Optional<String> logo = Optional.empty();

    private Optional<String> ogImage = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(BrandDesignSystemImages other) {
      favicon(other.getFavicon());
      logo(other.getLogo());
      ogImage(other.getOgImage());
      return this;
    }

    @JsonSetter(
        value = "favicon",
        nulls = Nulls.SKIP
    )
    public Builder favicon(Optional<String> favicon) {
      this.favicon = favicon;
      return this;
    }

    public Builder favicon(String favicon) {
      this.favicon = Optional.ofNullable(favicon);
      return this;
    }

    @JsonSetter(
        value = "logo",
        nulls = Nulls.SKIP
    )
    public Builder logo(Optional<String> logo) {
      this.logo = logo;
      return this;
    }

    public Builder logo(String logo) {
      this.logo = Optional.ofNullable(logo);
      return this;
    }

    @JsonSetter(
        value = "ogImage",
        nulls = Nulls.SKIP
    )
    public Builder ogImage(Optional<String> ogImage) {
      this.ogImage = ogImage;
      return this;
    }

    public Builder ogImage(String ogImage) {
      this.ogImage = Optional.ofNullable(ogImage);
      return this;
    }

    public BrandDesignSystemImages build() {
      return new BrandDesignSystemImages(favicon, logo, ogImage, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
