/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandProfileSocialsItem.Builder.class
)
public final class BrandProfileSocialsItem {
  private final String network;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private BrandProfileSocialsItem(String network, String url,
      Map<String, Object> additionalProperties) {
    this.network = network;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("network")
  public String getNetwork() {
    return network;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandProfileSocialsItem && equalTo((BrandProfileSocialsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandProfileSocialsItem other) {
    return network.equals(other.network) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.network, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NetworkStage builder() {
    return new Builder();
  }

  public interface NetworkStage {
    UrlStage network(@NotNull String network);

    Builder from(BrandProfileSocialsItem other);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    BrandProfileSocialsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NetworkStage, UrlStage, _FinalStage {
    private String network;

    private String url;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandProfileSocialsItem other) {
      network(other.getNetwork());
      url(other.getUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("network")
    public UrlStage network(@NotNull String network) {
      this.network = Objects.requireNonNull(network, "network must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public BrandProfileSocialsItem build() {
      return new BrandProfileSocialsItem(network, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
