/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ChangeTrackingFormatDtoType {
  public static final ChangeTrackingFormatDtoType CHANGE_TRACKING = new ChangeTrackingFormatDtoType(Value.CHANGE_TRACKING, "changeTracking");

  private final Value value;

  private final String string;

  ChangeTrackingFormatDtoType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ChangeTrackingFormatDtoType && this.string.equals(((ChangeTrackingFormatDtoType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CHANGE_TRACKING:
        return visitor.visitChangeTracking();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ChangeTrackingFormatDtoType valueOf(String value) {
    switch (value) {
      case "changeTracking":
        return CHANGE_TRACKING;
      default:
        return new ChangeTrackingFormatDtoType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CHANGE_TRACKING,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitChangeTracking();

    T visitUnknown(String unknownType);
  }
}
