/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import java.lang.Integer;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;

public interface IJobSummary {
  Optional<Integer> getCompleted();

  Optional<OffsetDateTime> getCompletedAt();

  OffsetDateTime getCreatedAt();

  int getCreditsUsed();

  Optional<String> getError();

  Optional<Integer> getFailed();

  String getId();

  Optional<OffsetDateTime> getStartedAt();

  String getStatus();

  int getTotal();

  JobSummaryType getType();
}
