/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = JobCreatedResponse.Builder.class
)
public final class JobCreatedResponse {
  private final String id;

  private final Optional<List<String>> invalidUrLs;

  private final boolean success;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private JobCreatedResponse(String id, Optional<List<String>> invalidUrLs, boolean success,
      String url, Map<String, Object> additionalProperties) {
    this.id = id;
    this.invalidUrLs = invalidUrLs;
    this.success = success;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("invalidURLs")
  public Optional<List<String>> getInvalidUrLs() {
    return invalidUrLs;
  }

  @JsonProperty("success")
  public boolean getSuccess() {
    return success;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof JobCreatedResponse && equalTo((JobCreatedResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(JobCreatedResponse other) {
    return id.equals(other.id) && invalidUrLs.equals(other.invalidUrLs) && success == other.success && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.invalidUrLs, this.success, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    SuccessStage id(@NotNull String id);

    Builder from(JobCreatedResponse other);
  }

  public interface SuccessStage {
    UrlStage success(boolean success);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    JobCreatedResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage invalidUrLs(Optional<List<String>> invalidUrLs);

    _FinalStage invalidUrLs(List<String> invalidUrLs);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, SuccessStage, UrlStage, _FinalStage {
    private String id;

    private boolean success;

    private String url;

    private Optional<List<String>> invalidUrLs = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(JobCreatedResponse other) {
      id(other.getId());
      invalidUrLs(other.getInvalidUrLs());
      success(other.getSuccess());
      url(other.getUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public SuccessStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("success")
    public UrlStage success(boolean success) {
      this.success = success;
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage invalidUrLs(List<String> invalidUrLs) {
      this.invalidUrLs = Optional.ofNullable(invalidUrLs);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "invalidURLs",
        nulls = Nulls.SKIP
    )
    public _FinalStage invalidUrLs(Optional<List<String>> invalidUrLs) {
      this.invalidUrLs = invalidUrLs;
      return this;
    }

    @java.lang.Override
    public JobCreatedResponse build() {
      return new JobCreatedResponse(id, invalidUrLs, success, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
