/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = JobResponseDataErrorsItem.Builder.class
)
public final class JobResponseDataErrorsItem {
  private final Optional<String> error;

  private final Optional<String> url;

  private final Map<String, Object> additionalProperties;

  private JobResponseDataErrorsItem(Optional<String> error, Optional<String> url,
      Map<String, Object> additionalProperties) {
    this.error = error;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("error")
  public Optional<String> getError() {
    return error;
  }

  @JsonProperty("url")
  public Optional<String> getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof JobResponseDataErrorsItem && equalTo((JobResponseDataErrorsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(JobResponseDataErrorsItem other) {
    return error.equals(other.error) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.error, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> error = Optional.empty();

    private Optional<String> url = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(JobResponseDataErrorsItem other) {
      error(other.getError());
      url(other.getUrl());
      return this;
    }

    @JsonSetter(
        value = "error",
        nulls = Nulls.SKIP
    )
    public Builder error(Optional<String> error) {
      this.error = error;
      return this;
    }

    public Builder error(String error) {
      this.error = Optional.ofNullable(error);
      return this;
    }

    @JsonSetter(
        value = "url",
        nulls = Nulls.SKIP
    )
    public Builder url(Optional<String> url) {
      this.url = url;
      return this;
    }

    public Builder url(String url) {
      this.url = Optional.ofNullable(url);
      return this;
    }

    public JobResponseDataErrorsItem build() {
      return new JobResponseDataErrorsItem(error, url, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
