/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.Nullable;
import com.berrycrawl.core.NullableNonemptyFilter;
import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = JobSummary.Builder.class
)
public final class JobSummary implements IJobSummary {
  private final Optional<Integer> completed;

  private final Optional<OffsetDateTime> completedAt;

  private final OffsetDateTime createdAt;

  private final int creditsUsed;

  private final Optional<String> error;

  private final Optional<Integer> failed;

  private final String id;

  private final Optional<OffsetDateTime> startedAt;

  private final String status;

  private final int total;

  private final JobSummaryType type;

  private final Map<String, Object> additionalProperties;

  private JobSummary(Optional<Integer> completed, Optional<OffsetDateTime> completedAt,
      OffsetDateTime createdAt, int creditsUsed, Optional<String> error, Optional<Integer> failed,
      String id, Optional<OffsetDateTime> startedAt, String status, int total, JobSummaryType type,
      Map<String, Object> additionalProperties) {
    this.completed = completed;
    this.completedAt = completedAt;
    this.createdAt = createdAt;
    this.creditsUsed = creditsUsed;
    this.error = error;
    this.failed = failed;
    this.id = id;
    this.startedAt = startedAt;
    this.status = status;
    this.total = total;
    this.type = type;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  @java.lang.Override
  public Optional<Integer> getCompleted() {
    if (completed == null) {
      return Optional.empty();
    }
    return completed;
  }

  @JsonIgnore
  @java.lang.Override
  public Optional<OffsetDateTime> getCompletedAt() {
    if (completedAt == null) {
      return Optional.empty();
    }
    return completedAt;
  }

  @JsonProperty("createdAt")
  @java.lang.Override
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("creditsUsed")
  @java.lang.Override
  public int getCreditsUsed() {
    return creditsUsed;
  }

  @JsonIgnore
  @java.lang.Override
  public Optional<String> getError() {
    if (error == null) {
      return Optional.empty();
    }
    return error;
  }

  @JsonIgnore
  @java.lang.Override
  public Optional<Integer> getFailed() {
    if (failed == null) {
      return Optional.empty();
    }
    return failed;
  }

  @JsonProperty("id")
  @java.lang.Override
  public String getId() {
    return id;
  }

  @JsonIgnore
  @java.lang.Override
  public Optional<OffsetDateTime> getStartedAt() {
    if (startedAt == null) {
      return Optional.empty();
    }
    return startedAt;
  }

  @JsonProperty("status")
  @java.lang.Override
  public String getStatus() {
    return status;
  }

  @JsonProperty("total")
  @java.lang.Override
  public int getTotal() {
    return total;
  }

  @JsonProperty("type")
  public JobSummaryType getType() {
    return type;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("completed")
  private Optional<Integer> _getCompleted() {
    return completed;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("completedAt")
  private Optional<OffsetDateTime> _getCompletedAt() {
    return completedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("error")
  private Optional<String> _getError() {
    return error;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("failed")
  private Optional<Integer> _getFailed() {
    return failed;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("startedAt")
  private Optional<OffsetDateTime> _getStartedAt() {
    return startedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof JobSummary && equalTo((JobSummary) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(JobSummary other) {
    return completed.equals(other.completed) && completedAt.equals(other.completedAt) && createdAt.equals(other.createdAt) && creditsUsed == other.creditsUsed && error.equals(other.error) && failed.equals(other.failed) && id.equals(other.id) && startedAt.equals(other.startedAt) && status.equals(other.status) && total == other.total && type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.completed, this.completedAt, this.createdAt, this.creditsUsed, this.error, this.failed, this.id, this.startedAt, this.status, this.total, this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CreatedAtStage builder() {
    return new Builder();
  }

  public interface CreatedAtStage {
    CreditsUsedStage createdAt(@NotNull OffsetDateTime createdAt);

    Builder from(JobSummary other);
  }

  public interface CreditsUsedStage {
    IdStage creditsUsed(int creditsUsed);
  }

  public interface IdStage {
    StatusStage id(@NotNull String id);
  }

  public interface StatusStage {
    TotalStage status(@NotNull String status);
  }

  public interface TotalStage {
    TypeStage total(int total);
  }

  public interface TypeStage {
    _FinalStage type(@NotNull JobSummaryType type);
  }

  public interface _FinalStage {
    JobSummary build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage completed(Optional<Integer> completed);

    _FinalStage completed(Integer completed);

    _FinalStage completed(Nullable<Integer> completed);

    _FinalStage completedAt(Optional<OffsetDateTime> completedAt);

    _FinalStage completedAt(OffsetDateTime completedAt);

    _FinalStage completedAt(Nullable<OffsetDateTime> completedAt);

    _FinalStage error(Optional<String> error);

    _FinalStage error(String error);

    _FinalStage error(Nullable<String> error);

    _FinalStage failed(Optional<Integer> failed);

    _FinalStage failed(Integer failed);

    _FinalStage failed(Nullable<Integer> failed);

    _FinalStage startedAt(Optional<OffsetDateTime> startedAt);

    _FinalStage startedAt(OffsetDateTime startedAt);

    _FinalStage startedAt(Nullable<OffsetDateTime> startedAt);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CreatedAtStage, CreditsUsedStage, IdStage, StatusStage, TotalStage, TypeStage, _FinalStage {
    private OffsetDateTime createdAt;

    private int creditsUsed;

    private String id;

    private String status;

    private int total;

    private JobSummaryType type;

    private Optional<OffsetDateTime> startedAt = Optional.empty();

    private Optional<Integer> failed = Optional.empty();

    private Optional<String> error = Optional.empty();

    private Optional<OffsetDateTime> completedAt = Optional.empty();

    private Optional<Integer> completed = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(JobSummary other) {
      completed(other.getCompleted());
      completedAt(other.getCompletedAt());
      createdAt(other.getCreatedAt());
      creditsUsed(other.getCreditsUsed());
      error(other.getError());
      failed(other.getFailed());
      id(other.getId());
      startedAt(other.getStartedAt());
      status(other.getStatus());
      total(other.getTotal());
      type(other.getType());
      return this;
    }

    @java.lang.Override
    @JsonSetter("createdAt")
    public CreditsUsedStage createdAt(@NotNull OffsetDateTime createdAt) {
      this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("creditsUsed")
    public IdStage creditsUsed(int creditsUsed) {
      this.creditsUsed = creditsUsed;
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public StatusStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public TotalStage status(@NotNull String status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("total")
    public TypeStage total(int total) {
      this.total = total;
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull JobSummaryType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage startedAt(Nullable<OffsetDateTime> startedAt) {
      if (startedAt.isNull()) {
        this.startedAt = null;
      }
      else if (startedAt.isEmpty()) {
        this.startedAt = Optional.empty();
      }
      else {
        this.startedAt = Optional.of(startedAt.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage startedAt(OffsetDateTime startedAt) {
      this.startedAt = Optional.ofNullable(startedAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "startedAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage startedAt(Optional<OffsetDateTime> startedAt) {
      this.startedAt = startedAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage failed(Nullable<Integer> failed) {
      if (failed.isNull()) {
        this.failed = null;
      }
      else if (failed.isEmpty()) {
        this.failed = Optional.empty();
      }
      else {
        this.failed = Optional.of(failed.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage failed(Integer failed) {
      this.failed = Optional.ofNullable(failed);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "failed",
        nulls = Nulls.SKIP
    )
    public _FinalStage failed(Optional<Integer> failed) {
      this.failed = failed;
      return this;
    }

    @java.lang.Override
    public _FinalStage error(Nullable<String> error) {
      if (error.isNull()) {
        this.error = null;
      }
      else if (error.isEmpty()) {
        this.error = Optional.empty();
      }
      else {
        this.error = Optional.of(error.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage error(String error) {
      this.error = Optional.ofNullable(error);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "error",
        nulls = Nulls.SKIP
    )
    public _FinalStage error(Optional<String> error) {
      this.error = error;
      return this;
    }

    @java.lang.Override
    public _FinalStage completedAt(Nullable<OffsetDateTime> completedAt) {
      if (completedAt.isNull()) {
        this.completedAt = null;
      }
      else if (completedAt.isEmpty()) {
        this.completedAt = Optional.empty();
      }
      else {
        this.completedAt = Optional.of(completedAt.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage completedAt(OffsetDateTime completedAt) {
      this.completedAt = Optional.ofNullable(completedAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "completedAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage completedAt(Optional<OffsetDateTime> completedAt) {
      this.completedAt = completedAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage completed(Nullable<Integer> completed) {
      if (completed.isNull()) {
        this.completed = null;
      }
      else if (completed.isEmpty()) {
        this.completed = Optional.empty();
      }
      else {
        this.completed = Optional.of(completed.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage completed(Integer completed) {
      this.completed = Optional.ofNullable(completed);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "completed",
        nulls = Nulls.SKIP
    )
    public _FinalStage completed(Optional<Integer> completed) {
      this.completed = completed;
      return this;
    }

    @java.lang.Override
    public JobSummary build() {
      return new JobSummary(completed, completedAt, createdAt, creditsUsed, error, failed, id, startedAt, status, total, type, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
