/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = JsonFormatDto.Builder.class
)
public final class JsonFormatDto {
  private final Optional<String> prompt;

  private final Map<String, Object> schema;

  private final JsonFormatDtoType type;

  private final Map<String, Object> additionalProperties;

  private JsonFormatDto(Optional<String> prompt, Map<String, Object> schema, JsonFormatDtoType type,
      Map<String, Object> additionalProperties) {
    this.prompt = prompt;
    this.schema = schema;
    this.type = type;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Natural language prompt for extraction guidance
   */
  @JsonProperty("prompt")
  public Optional<String> getPrompt() {
    return prompt;
  }

  /**
   * @return JSON schema for structured extraction
   */
  @JsonProperty("schema")
  public Map<String, Object> getSchema() {
    return schema;
  }

  /**
   * @return Format type
   */
  @JsonProperty("type")
  public JsonFormatDtoType getType() {
    return type;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof JsonFormatDto && equalTo((JsonFormatDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(JsonFormatDto other) {
    return prompt.equals(other.prompt) && schema.equals(other.schema) && type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.prompt, this.schema, this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    /**
     * <p>Format type</p>
     */
    _FinalStage type(@NotNull JsonFormatDtoType type);

    Builder from(JsonFormatDto other);
  }

  public interface _FinalStage {
    JsonFormatDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Natural language prompt for extraction guidance</p>
     */
    _FinalStage prompt(Optional<String> prompt);

    _FinalStage prompt(String prompt);

    /**
     * <p>JSON schema for structured extraction</p>
     */
    _FinalStage schema(Map<String, Object> schema);

    _FinalStage putAllSchema(Map<String, Object> schema);

    _FinalStage schema(String key, Object value);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, _FinalStage {
    private JsonFormatDtoType type;

    private Map<String, Object> schema = new LinkedHashMap<>();

    private Optional<String> prompt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(JsonFormatDto other) {
      prompt(other.getPrompt());
      schema(other.getSchema());
      type(other.getType());
      return this;
    }

    /**
     * <p>Format type</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull JsonFormatDtoType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>JSON schema for structured extraction</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage schema(String key, Object value) {
      this.schema.put(key, value);
      return this;
    }

    /**
     * <p>JSON schema for structured extraction</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage putAllSchema(Map<String, Object> schema) {
      if (schema != null) {
        this.schema.putAll(schema);
      }
      return this;
    }

    /**
     * <p>JSON schema for structured extraction</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "schema",
        nulls = Nulls.SKIP
    )
    public _FinalStage schema(Map<String, Object> schema) {
      this.schema.clear();
      if (schema != null) {
        this.schema.putAll(schema);
      }
      return this;
    }

    /**
     * <p>Natural language prompt for extraction guidance</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage prompt(String prompt) {
      this.prompt = Optional.ofNullable(prompt);
      return this;
    }

    /**
     * <p>Natural language prompt for extraction guidance</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "prompt",
        nulls = Nulls.SKIP
    )
    public _FinalStage prompt(Optional<String> prompt) {
      this.prompt = prompt;
      return this;
    }

    @java.lang.Override
    public JsonFormatDto build() {
      return new JsonFormatDto(prompt, schema, type, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
