/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListJobsResponseData.Builder.class
)
public final class ListJobsResponseData {
  private final List<JobSummary> jobs;

  private final Pagination pagination;

  private final Map<String, Object> additionalProperties;

  private ListJobsResponseData(List<JobSummary> jobs, Pagination pagination,
      Map<String, Object> additionalProperties) {
    this.jobs = jobs;
    this.pagination = pagination;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("jobs")
  public List<JobSummary> getJobs() {
    return jobs;
  }

  @JsonProperty("pagination")
  public Pagination getPagination() {
    return pagination;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListJobsResponseData && equalTo((ListJobsResponseData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListJobsResponseData other) {
    return jobs.equals(other.jobs) && pagination.equals(other.pagination);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.jobs, this.pagination);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PaginationStage builder() {
    return new Builder();
  }

  public interface PaginationStage {
    _FinalStage pagination(@NotNull Pagination pagination);

    Builder from(ListJobsResponseData other);
  }

  public interface _FinalStage {
    ListJobsResponseData build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage jobs(List<JobSummary> jobs);

    _FinalStage addJobs(JobSummary jobs);

    _FinalStage addAllJobs(List<JobSummary> jobs);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PaginationStage, _FinalStage {
    private Pagination pagination;

    private List<JobSummary> jobs = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListJobsResponseData other) {
      jobs(other.getJobs());
      pagination(other.getPagination());
      return this;
    }

    @java.lang.Override
    @JsonSetter("pagination")
    public _FinalStage pagination(@NotNull Pagination pagination) {
      this.pagination = Objects.requireNonNull(pagination, "pagination must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllJobs(List<JobSummary> jobs) {
      if (jobs != null) {
        this.jobs.addAll(jobs);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addJobs(JobSummary jobs) {
      this.jobs.add(jobs);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "jobs",
        nulls = Nulls.SKIP
    )
    public _FinalStage jobs(List<JobSummary> jobs) {
      this.jobs.clear();
      if (jobs != null) {
        this.jobs.addAll(jobs);
      }
      return this;
    }

    @java.lang.Override
    public ListJobsResponseData build() {
      return new ListJobsResponseData(jobs, pagination, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
