/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListJobsResponse.Builder.class
)
public final class ListJobsResponse {
  private final ListJobsResponseData data;

  private final boolean success;

  private final Map<String, Object> additionalProperties;

  private ListJobsResponse(ListJobsResponseData data, boolean success,
      Map<String, Object> additionalProperties) {
    this.data = data;
    this.success = success;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("data")
  public ListJobsResponseData getData() {
    return data;
  }

  @JsonProperty("success")
  public boolean getSuccess() {
    return success;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListJobsResponse && equalTo((ListJobsResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListJobsResponse other) {
    return data.equals(other.data) && success == other.success;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.data, this.success);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DataStage builder() {
    return new Builder();
  }

  public interface DataStage {
    SuccessStage data(@NotNull ListJobsResponseData data);

    Builder from(ListJobsResponse other);
  }

  public interface SuccessStage {
    _FinalStage success(boolean success);
  }

  public interface _FinalStage {
    ListJobsResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DataStage, SuccessStage, _FinalStage {
    private ListJobsResponseData data;

    private boolean success;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListJobsResponse other) {
      data(other.getData());
      success(other.getSuccess());
      return this;
    }

    @java.lang.Override
    @JsonSetter("data")
    public SuccessStage data(@NotNull ListJobsResponseData data) {
      this.data = Objects.requireNonNull(data, "data must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("success")
    public _FinalStage success(boolean success) {
      this.success = success;
      return this;
    }

    @java.lang.Override
    public ListJobsResponse build() {
      return new ListJobsResponse(data, success, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
