/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ListWebhooksResponse.Builder.class
)
public final class ListWebhooksResponse {
  private final List<Webhook> data;

  private final boolean success;

  private final Map<String, Object> additionalProperties;

  private ListWebhooksResponse(List<Webhook> data, boolean success,
      Map<String, Object> additionalProperties) {
    this.data = data;
    this.success = success;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("data")
  public List<Webhook> getData() {
    return data;
  }

  @JsonProperty("success")
  public boolean getSuccess() {
    return success;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ListWebhooksResponse && equalTo((ListWebhooksResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ListWebhooksResponse other) {
    return data.equals(other.data) && success == other.success;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.data, this.success);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SuccessStage builder() {
    return new Builder();
  }

  public interface SuccessStage {
    _FinalStage success(boolean success);

    Builder from(ListWebhooksResponse other);
  }

  public interface _FinalStage {
    ListWebhooksResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage data(List<Webhook> data);

    _FinalStage addData(Webhook data);

    _FinalStage addAllData(List<Webhook> data);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SuccessStage, _FinalStage {
    private boolean success;

    private List<Webhook> data = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ListWebhooksResponse other) {
      data(other.getData());
      success(other.getSuccess());
      return this;
    }

    @java.lang.Override
    @JsonSetter("success")
    public _FinalStage success(boolean success) {
      this.success = success;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllData(List<Webhook> data) {
      if (data != null) {
        this.data.addAll(data);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addData(Webhook data) {
      this.data.add(data);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public _FinalStage data(List<Webhook> data) {
      this.data.clear();
      if (data != null) {
        this.data.addAll(data);
      }
      return this;
    }

    @java.lang.Override
    public ListWebhooksResponse build() {
      return new ListWebhooksResponse(data, success, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
