/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class MapDtoSitemap {
  public static final MapDtoSitemap INCLUDE = new MapDtoSitemap(Value.INCLUDE, "include");

  public static final MapDtoSitemap ONLY = new MapDtoSitemap(Value.ONLY, "only");

  public static final MapDtoSitemap SKIP = new MapDtoSitemap(Value.SKIP, "skip");

  private final Value value;

  private final String string;

  MapDtoSitemap(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof MapDtoSitemap && this.string.equals(((MapDtoSitemap) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case INCLUDE:
        return visitor.visitInclude();
      case ONLY:
        return visitor.visitOnly();
      case SKIP:
        return visitor.visitSkip();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static MapDtoSitemap valueOf(String value) {
    switch (value) {
      case "include":
        return INCLUDE;
      case "only":
        return ONLY;
      case "skip":
        return SKIP;
      default:
        return new MapDtoSitemap(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    INCLUDE,

    SKIP,

    ONLY,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitInclude();

    T visitSkip();

    T visitOnly();

    T visitUnknown(String unknownType);
  }
}
