/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Pagination.Builder.class
)
public final class Pagination {
  private final int limit;

  private final int page;

  private final int total;

  private final Optional<Integer> totalPages;

  private final Map<String, Object> additionalProperties;

  private Pagination(int limit, int page, int total, Optional<Integer> totalPages,
      Map<String, Object> additionalProperties) {
    this.limit = limit;
    this.page = page;
    this.total = total;
    this.totalPages = totalPages;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("limit")
  public int getLimit() {
    return limit;
  }

  @JsonProperty("page")
  public int getPage() {
    return page;
  }

  @JsonProperty("total")
  public int getTotal() {
    return total;
  }

  @JsonProperty("totalPages")
  public Optional<Integer> getTotalPages() {
    return totalPages;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Pagination && equalTo((Pagination) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Pagination other) {
    return limit == other.limit && page == other.page && total == other.total && totalPages.equals(other.totalPages);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.limit, this.page, this.total, this.totalPages);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static LimitStage builder() {
    return new Builder();
  }

  public interface LimitStage {
    PageStage limit(int limit);

    Builder from(Pagination other);
  }

  public interface PageStage {
    TotalStage page(int page);
  }

  public interface TotalStage {
    _FinalStage total(int total);
  }

  public interface _FinalStage {
    Pagination build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage totalPages(Optional<Integer> totalPages);

    _FinalStage totalPages(Integer totalPages);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements LimitStage, PageStage, TotalStage, _FinalStage {
    private int limit;

    private int page;

    private int total;

    private Optional<Integer> totalPages = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Pagination other) {
      limit(other.getLimit());
      page(other.getPage());
      total(other.getTotal());
      totalPages(other.getTotalPages());
      return this;
    }

    @java.lang.Override
    @JsonSetter("limit")
    public PageStage limit(int limit) {
      this.limit = limit;
      return this;
    }

    @java.lang.Override
    @JsonSetter("page")
    public TotalStage page(int page) {
      this.page = page;
      return this;
    }

    @java.lang.Override
    @JsonSetter("total")
    public _FinalStage total(int total) {
      this.total = total;
      return this;
    }

    @java.lang.Override
    public _FinalStage totalPages(Integer totalPages) {
      this.totalPages = Optional.ofNullable(totalPages);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "totalPages",
        nulls = Nulls.SKIP
    )
    public _FinalStage totalPages(Optional<Integer> totalPages) {
      this.totalPages = totalPages;
      return this;
    }

    @java.lang.Override
    public Pagination build() {
      return new Pagination(limit, page, total, totalPages, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
