/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScrapeMetadata.Builder.class
)
public final class ScrapeMetadata {
  private final Optional<String> contentType;

  private final Optional<Integer> statusCode;

  private final OffsetDateTime timestamp;

  private final Optional<String> title;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private ScrapeMetadata(Optional<String> contentType, Optional<Integer> statusCode,
      OffsetDateTime timestamp, Optional<String> title, String url,
      Map<String, Object> additionalProperties) {
    this.contentType = contentType;
    this.statusCode = statusCode;
    this.timestamp = timestamp;
    this.title = title;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("contentType")
  public Optional<String> getContentType() {
    return contentType;
  }

  @JsonProperty("statusCode")
  public Optional<Integer> getStatusCode() {
    return statusCode;
  }

  @JsonProperty("timestamp")
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  @JsonProperty("title")
  public Optional<String> getTitle() {
    return title;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScrapeMetadata && equalTo((ScrapeMetadata) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScrapeMetadata other) {
    return contentType.equals(other.contentType) && statusCode.equals(other.statusCode) && timestamp.equals(other.timestamp) && title.equals(other.title) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.contentType, this.statusCode, this.timestamp, this.title, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TimestampStage builder() {
    return new Builder();
  }

  public interface TimestampStage {
    UrlStage timestamp(@NotNull OffsetDateTime timestamp);

    Builder from(ScrapeMetadata other);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    ScrapeMetadata build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage contentType(Optional<String> contentType);

    _FinalStage contentType(String contentType);

    _FinalStage statusCode(Optional<Integer> statusCode);

    _FinalStage statusCode(Integer statusCode);

    _FinalStage title(Optional<String> title);

    _FinalStage title(String title);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TimestampStage, UrlStage, _FinalStage {
    private OffsetDateTime timestamp;

    private String url;

    private Optional<String> title = Optional.empty();

    private Optional<Integer> statusCode = Optional.empty();

    private Optional<String> contentType = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ScrapeMetadata other) {
      contentType(other.getContentType());
      statusCode(other.getStatusCode());
      timestamp(other.getTimestamp());
      title(other.getTitle());
      url(other.getUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("timestamp")
    public UrlStage timestamp(@NotNull OffsetDateTime timestamp) {
      this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage title(String title) {
      this.title = Optional.ofNullable(title);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "title",
        nulls = Nulls.SKIP
    )
    public _FinalStage title(Optional<String> title) {
      this.title = title;
      return this;
    }

    @java.lang.Override
    public _FinalStage statusCode(Integer statusCode) {
      this.statusCode = Optional.ofNullable(statusCode);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "statusCode",
        nulls = Nulls.SKIP
    )
    public _FinalStage statusCode(Optional<Integer> statusCode) {
      this.statusCode = statusCode;
      return this;
    }

    @java.lang.Override
    public _FinalStage contentType(String contentType) {
      this.contentType = Optional.ofNullable(contentType);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "contentType",
        nulls = Nulls.SKIP
    )
    public _FinalStage contentType(Optional<String> contentType) {
      this.contentType = contentType;
      return this;
    }

    @java.lang.Override
    public ScrapeMetadata build() {
      return new ScrapeMetadata(contentType, statusCode, timestamp, title, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
