/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScrapeResponse.Builder.class
)
public final class ScrapeResponse {
  private final ScrapeResponseCredits credits;

  private final Optional<Map<String, Object>> data;

  private final Optional<String> error;

  private final ScrapeMetadata metadata;

  private final boolean success;

  private final Map<String, Object> additionalProperties;

  private ScrapeResponse(ScrapeResponseCredits credits, Optional<Map<String, Object>> data,
      Optional<String> error, ScrapeMetadata metadata, boolean success,
      Map<String, Object> additionalProperties) {
    this.credits = credits;
    this.data = data;
    this.error = error;
    this.metadata = metadata;
    this.success = success;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("credits")
  public ScrapeResponseCredits getCredits() {
    return credits;
  }

  @JsonProperty("data")
  public Optional<Map<String, Object>> getData() {
    return data;
  }

  @JsonProperty("error")
  public Optional<String> getError() {
    return error;
  }

  @JsonProperty("metadata")
  public ScrapeMetadata getMetadata() {
    return metadata;
  }

  @JsonProperty("success")
  public boolean getSuccess() {
    return success;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScrapeResponse && equalTo((ScrapeResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScrapeResponse other) {
    return credits.equals(other.credits) && data.equals(other.data) && error.equals(other.error) && metadata.equals(other.metadata) && success == other.success;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.credits, this.data, this.error, this.metadata, this.success);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CreditsStage builder() {
    return new Builder();
  }

  public interface CreditsStage {
    MetadataStage credits(@NotNull ScrapeResponseCredits credits);

    Builder from(ScrapeResponse other);
  }

  public interface MetadataStage {
    SuccessStage metadata(@NotNull ScrapeMetadata metadata);
  }

  public interface SuccessStage {
    _FinalStage success(boolean success);
  }

  public interface _FinalStage {
    ScrapeResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage data(Optional<Map<String, Object>> data);

    _FinalStage data(Map<String, Object> data);

    _FinalStage error(Optional<String> error);

    _FinalStage error(String error);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CreditsStage, MetadataStage, SuccessStage, _FinalStage {
    private ScrapeResponseCredits credits;

    private ScrapeMetadata metadata;

    private boolean success;

    private Optional<String> error = Optional.empty();

    private Optional<Map<String, Object>> data = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ScrapeResponse other) {
      credits(other.getCredits());
      data(other.getData());
      error(other.getError());
      metadata(other.getMetadata());
      success(other.getSuccess());
      return this;
    }

    @java.lang.Override
    @JsonSetter("credits")
    public MetadataStage credits(@NotNull ScrapeResponseCredits credits) {
      this.credits = Objects.requireNonNull(credits, "credits must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("metadata")
    public SuccessStage metadata(@NotNull ScrapeMetadata metadata) {
      this.metadata = Objects.requireNonNull(metadata, "metadata must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("success")
    public _FinalStage success(boolean success) {
      this.success = success;
      return this;
    }

    @java.lang.Override
    public _FinalStage error(String error) {
      this.error = Optional.ofNullable(error);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "error",
        nulls = Nulls.SKIP
    )
    public _FinalStage error(Optional<String> error) {
      this.error = error;
      return this;
    }

    @java.lang.Override
    public _FinalStage data(Map<String, Object> data) {
      this.data = Optional.ofNullable(data);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public _FinalStage data(Optional<Map<String, Object>> data) {
      this.data = data;
      return this;
    }

    @java.lang.Override
    public ScrapeResponse build() {
      return new ScrapeResponse(credits, data, error, metadata, success, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
