/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ScrapeDtoFormatsItemZero {
  public static final ScrapeDtoFormatsItemZero IMAGES = new ScrapeDtoFormatsItemZero(Value.IMAGES, "images");

  public static final ScrapeDtoFormatsItemZero LINKS = new ScrapeDtoFormatsItemZero(Value.LINKS, "links");

  public static final ScrapeDtoFormatsItemZero CHANGE_TRACKING = new ScrapeDtoFormatsItemZero(Value.CHANGE_TRACKING, "changeTracking");

  public static final ScrapeDtoFormatsItemZero MARKDOWN = new ScrapeDtoFormatsItemZero(Value.MARKDOWN, "markdown");

  public static final ScrapeDtoFormatsItemZero RAWHTML = new ScrapeDtoFormatsItemZero(Value.RAWHTML, "rawhtml");

  public static final ScrapeDtoFormatsItemZero HTML = new ScrapeDtoFormatsItemZero(Value.HTML, "html");

  public static final ScrapeDtoFormatsItemZero JSON = new ScrapeDtoFormatsItemZero(Value.JSON, "json");

  public static final ScrapeDtoFormatsItemZero SUMMARY = new ScrapeDtoFormatsItemZero(Value.SUMMARY, "summary");

  private final Value value;

  private final String string;

  ScrapeDtoFormatsItemZero(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ScrapeDtoFormatsItemZero && this.string.equals(((ScrapeDtoFormatsItemZero) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case IMAGES:
        return visitor.visitImages();
      case LINKS:
        return visitor.visitLinks();
      case CHANGE_TRACKING:
        return visitor.visitChangeTracking();
      case MARKDOWN:
        return visitor.visitMarkdown();
      case RAWHTML:
        return visitor.visitRawhtml();
      case HTML:
        return visitor.visitHtml();
      case JSON:
        return visitor.visitJson();
      case SUMMARY:
        return visitor.visitSummary();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ScrapeDtoFormatsItemZero valueOf(String value) {
    switch (value) {
      case "images":
        return IMAGES;
      case "links":
        return LINKS;
      case "changeTracking":
        return CHANGE_TRACKING;
      case "markdown":
        return MARKDOWN;
      case "rawhtml":
        return RAWHTML;
      case "html":
        return HTML;
      case "json":
        return JSON;
      case "summary":
        return SUMMARY;
      default:
        return new ScrapeDtoFormatsItemZero(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    MARKDOWN,

    HTML,

    RAWHTML,

    LINKS,

    IMAGES,

    SUMMARY,

    JSON,

    CHANGE_TRACKING,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitMarkdown();

    T visitHtml();

    T visitRawhtml();

    T visitLinks();

    T visitImages();

    T visitSummary();

    T visitJson();

    T visitChangeTracking();

    T visitUnknown(String unknownType);
  }
}
