/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScrapeResponseCredits.Builder.class
)
public final class ScrapeResponseCredits {
  private final int used;

  private final Map<String, Object> additionalProperties;

  private ScrapeResponseCredits(int used, Map<String, Object> additionalProperties) {
    this.used = used;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("used")
  public int getUsed() {
    return used;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScrapeResponseCredits && equalTo((ScrapeResponseCredits) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScrapeResponseCredits other) {
    return used == other.used;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.used);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UsedStage builder() {
    return new Builder();
  }

  public interface UsedStage {
    _FinalStage used(int used);

    Builder from(ScrapeResponseCredits other);
  }

  public interface _FinalStage {
    ScrapeResponseCredits build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UsedStage, _FinalStage {
    private int used;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ScrapeResponseCredits other) {
      used(other.getUsed());
      return this;
    }

    @java.lang.Override
    @JsonSetter("used")
    public _FinalStage used(int used) {
      this.used = used;
      return this;
    }

    @java.lang.Override
    public ScrapeResponseCredits build() {
      return new ScrapeResponseCredits(used, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
