/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ScreenshotDtoFormat {
  public static final ScreenshotDtoFormat WEBP = new ScreenshotDtoFormat(Value.WEBP, "webp");

  public static final ScreenshotDtoFormat JPEG = new ScreenshotDtoFormat(Value.JPEG, "jpeg");

  public static final ScreenshotDtoFormat PNG = new ScreenshotDtoFormat(Value.PNG, "png");

  private final Value value;

  private final String string;

  ScreenshotDtoFormat(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ScreenshotDtoFormat && this.string.equals(((ScreenshotDtoFormat) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case WEBP:
        return visitor.visitWebp();
      case JPEG:
        return visitor.visitJpeg();
      case PNG:
        return visitor.visitPng();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ScreenshotDtoFormat valueOf(String value) {
    switch (value) {
      case "webp":
        return WEBP;
      case "jpeg":
        return JPEG;
      case "png":
        return PNG;
      default:
        return new ScreenshotDtoFormat(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PNG,

    JPEG,

    WEBP,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPng();

    T visitJpeg();

    T visitWebp();

    T visitUnknown(String unknownType);
  }
}
