/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ScreenshotDtoWaitUntil {
  public static final ScreenshotDtoWaitUntil NETWORKIDLE = new ScreenshotDtoWaitUntil(Value.NETWORKIDLE, "networkidle");

  public static final ScreenshotDtoWaitUntil LOAD = new ScreenshotDtoWaitUntil(Value.LOAD, "load");

  public static final ScreenshotDtoWaitUntil DOMCONTENTLOADED = new ScreenshotDtoWaitUntil(Value.DOMCONTENTLOADED, "domcontentloaded");

  private final Value value;

  private final String string;

  ScreenshotDtoWaitUntil(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ScreenshotDtoWaitUntil && this.string.equals(((ScreenshotDtoWaitUntil) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case NETWORKIDLE:
        return visitor.visitNetworkidle();
      case LOAD:
        return visitor.visitLoad();
      case DOMCONTENTLOADED:
        return visitor.visitDomcontentloaded();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ScreenshotDtoWaitUntil valueOf(String value) {
    switch (value) {
      case "networkidle":
        return NETWORKIDLE;
      case "load":
        return LOAD;
      case "domcontentloaded":
        return DOMCONTENTLOADED;
      default:
        return new ScreenshotDtoWaitUntil(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    DOMCONTENTLOADED,

    LOAD,

    NETWORKIDLE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitDomcontentloaded();

    T visitLoad();

    T visitNetworkidle();

    T visitUnknown(String unknownType);
  }
}
