/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScreenshotViewportDto.Builder.class
)
public final class ScreenshotViewportDto {
  private final double height;

  private final double width;

  private final Map<String, Object> additionalProperties;

  private ScreenshotViewportDto(double height, double width,
      Map<String, Object> additionalProperties) {
    this.height = height;
    this.width = width;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("height")
  public double getHeight() {
    return height;
  }

  @JsonProperty("width")
  public double getWidth() {
    return width;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScreenshotViewportDto && equalTo((ScreenshotViewportDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScreenshotViewportDto other) {
    return height == other.height && width == other.width;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.height, this.width);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static HeightStage builder() {
    return new Builder();
  }

  public interface HeightStage {
    WidthStage height(double height);

    Builder from(ScreenshotViewportDto other);
  }

  public interface WidthStage {
    _FinalStage width(double width);
  }

  public interface _FinalStage {
    ScreenshotViewportDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements HeightStage, WidthStage, _FinalStage {
    private double height;

    private double width;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ScreenshotViewportDto other) {
      height(other.getHeight());
      width(other.getWidth());
      return this;
    }

    @java.lang.Override
    @JsonSetter("height")
    public WidthStage height(double height) {
      this.height = height;
      return this;
    }

    @java.lang.Override
    @JsonSetter("width")
    public _FinalStage width(double width) {
      this.width = width;
      return this;
    }

    @java.lang.Override
    public ScreenshotViewportDto build() {
      return new ScreenshotViewportDto(height, width, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
