/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ScreenshotDtoScale {
  public static final ScreenshotDtoScale CSS = new ScreenshotDtoScale(Value.CSS, "css");

  public static final ScreenshotDtoScale DEVICE = new ScreenshotDtoScale(Value.DEVICE, "device");

  private final Value value;

  private final String string;

  ScreenshotDtoScale(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ScreenshotDtoScale && this.string.equals(((ScreenshotDtoScale) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CSS:
        return visitor.visitCss();
      case DEVICE:
        return visitor.visitDevice();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ScreenshotDtoScale valueOf(String value) {
    switch (value) {
      case "css":
        return CSS;
      case "device":
        return DEVICE;
      default:
        return new ScreenshotDtoScale(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CSS,

    DEVICE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCss();

    T visitDevice();

    T visitUnknown(String unknownType);
  }
}
