/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ScreenshotDtoFullPageAlgorithm {
  public static final ScreenshotDtoFullPageAlgorithm STITCH = new ScreenshotDtoFullPageAlgorithm(Value.STITCH, "stitch");

  public static final ScreenshotDtoFullPageAlgorithm NATIVE = new ScreenshotDtoFullPageAlgorithm(Value.NATIVE, "native");

  public static final ScreenshotDtoFullPageAlgorithm AUTO = new ScreenshotDtoFullPageAlgorithm(Value.AUTO, "auto");

  private final Value value;

  private final String string;

  ScreenshotDtoFullPageAlgorithm(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ScreenshotDtoFullPageAlgorithm && this.string.equals(((ScreenshotDtoFullPageAlgorithm) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case STITCH:
        return visitor.visitStitch();
      case NATIVE:
        return visitor.visitNative();
      case AUTO:
        return visitor.visitAuto();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ScreenshotDtoFullPageAlgorithm valueOf(String value) {
    switch (value) {
      case "stitch":
        return STITCH;
      case "native":
        return NATIVE;
      case "auto":
        return AUTO;
      default:
        return new ScreenshotDtoFullPageAlgorithm(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    AUTO,

    NATIVE,

    STITCH,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitAuto();

    T visitNative();

    T visitStitch();

    T visitUnknown(String unknownType);
  }
}
