/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScreenshotCookieDto.Builder.class
)
public final class ScreenshotCookieDto {
  private final Optional<String> domain;

  private final Optional<Boolean> httpOnly;

  private final String name;

  private final Optional<String> path;

  private final Optional<ScreenshotCookieDtoSameSite> sameSite;

  private final Optional<Boolean> secure;

  private final String value;

  private final Map<String, Object> additionalProperties;

  private ScreenshotCookieDto(Optional<String> domain, Optional<Boolean> httpOnly, String name,
      Optional<String> path, Optional<ScreenshotCookieDtoSameSite> sameSite,
      Optional<Boolean> secure, String value, Map<String, Object> additionalProperties) {
    this.domain = domain;
    this.httpOnly = httpOnly;
    this.name = name;
    this.path = path;
    this.sameSite = sameSite;
    this.secure = secure;
    this.value = value;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("domain")
  public Optional<String> getDomain() {
    return domain;
  }

  @JsonProperty("httpOnly")
  public Optional<Boolean> getHttpOnly() {
    return httpOnly;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonProperty("path")
  public Optional<String> getPath() {
    return path;
  }

  @JsonProperty("sameSite")
  public Optional<ScreenshotCookieDtoSameSite> getSameSite() {
    return sameSite;
  }

  @JsonProperty("secure")
  public Optional<Boolean> getSecure() {
    return secure;
  }

  @JsonProperty("value")
  public String getValue() {
    return value;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScreenshotCookieDto && equalTo((ScreenshotCookieDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScreenshotCookieDto other) {
    return domain.equals(other.domain) && httpOnly.equals(other.httpOnly) && name.equals(other.name) && path.equals(other.path) && sameSite.equals(other.sameSite) && secure.equals(other.secure) && value.equals(other.value);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.domain, this.httpOnly, this.name, this.path, this.sameSite, this.secure, this.value);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static NameStage builder() {
    return new Builder();
  }

  public interface NameStage {
    ValueStage name(@NotNull String name);

    Builder from(ScreenshotCookieDto other);
  }

  public interface ValueStage {
    _FinalStage value(@NotNull String value);
  }

  public interface _FinalStage {
    ScreenshotCookieDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage domain(Optional<String> domain);

    _FinalStage domain(String domain);

    _FinalStage httpOnly(Optional<Boolean> httpOnly);

    _FinalStage httpOnly(Boolean httpOnly);

    _FinalStage path(Optional<String> path);

    _FinalStage path(String path);

    _FinalStage sameSite(Optional<ScreenshotCookieDtoSameSite> sameSite);

    _FinalStage sameSite(ScreenshotCookieDtoSameSite sameSite);

    _FinalStage secure(Optional<Boolean> secure);

    _FinalStage secure(Boolean secure);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements NameStage, ValueStage, _FinalStage {
    private String name;

    private String value;

    private Optional<Boolean> secure = Optional.empty();

    private Optional<ScreenshotCookieDtoSameSite> sameSite = Optional.empty();

    private Optional<String> path = Optional.empty();

    private Optional<Boolean> httpOnly = Optional.empty();

    private Optional<String> domain = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ScreenshotCookieDto other) {
      domain(other.getDomain());
      httpOnly(other.getHttpOnly());
      name(other.getName());
      path(other.getPath());
      sameSite(other.getSameSite());
      secure(other.getSecure());
      value(other.getValue());
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public ValueStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("value")
    public _FinalStage value(@NotNull String value) {
      this.value = Objects.requireNonNull(value, "value must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage secure(Boolean secure) {
      this.secure = Optional.ofNullable(secure);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "secure",
        nulls = Nulls.SKIP
    )
    public _FinalStage secure(Optional<Boolean> secure) {
      this.secure = secure;
      return this;
    }

    @java.lang.Override
    public _FinalStage sameSite(ScreenshotCookieDtoSameSite sameSite) {
      this.sameSite = Optional.ofNullable(sameSite);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "sameSite",
        nulls = Nulls.SKIP
    )
    public _FinalStage sameSite(Optional<ScreenshotCookieDtoSameSite> sameSite) {
      this.sameSite = sameSite;
      return this;
    }

    @java.lang.Override
    public _FinalStage path(String path) {
      this.path = Optional.ofNullable(path);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "path",
        nulls = Nulls.SKIP
    )
    public _FinalStage path(Optional<String> path) {
      this.path = path;
      return this;
    }

    @java.lang.Override
    public _FinalStage httpOnly(Boolean httpOnly) {
      this.httpOnly = Optional.ofNullable(httpOnly);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "httpOnly",
        nulls = Nulls.SKIP
    )
    public _FinalStage httpOnly(Optional<Boolean> httpOnly) {
      this.httpOnly = httpOnly;
      return this;
    }

    @java.lang.Override
    public _FinalStage domain(String domain) {
      this.domain = Optional.ofNullable(domain);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "domain",
        nulls = Nulls.SKIP
    )
    public _FinalStage domain(Optional<String> domain) {
      this.domain = domain;
      return this;
    }

    @java.lang.Override
    public ScreenshotCookieDto build() {
      return new ScreenshotCookieDto(domain, httpOnly, name, path, sameSite, secure, value, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
