/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScreenshotLocationDto.Builder.class
)
public final class ScreenshotLocationDto {
  private final Optional<String> country;

  private final Optional<List<String>> languages;

  private final Map<String, Object> additionalProperties;

  private ScreenshotLocationDto(Optional<String> country, Optional<List<String>> languages,
      Map<String, Object> additionalProperties) {
    this.country = country;
    this.languages = languages;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("country")
  public Optional<String> getCountry() {
    return country;
  }

  @JsonProperty("languages")
  public Optional<List<String>> getLanguages() {
    return languages;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScreenshotLocationDto && equalTo((ScreenshotLocationDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScreenshotLocationDto other) {
    return country.equals(other.country) && languages.equals(other.languages);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.country, this.languages);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> country = Optional.empty();

    private Optional<List<String>> languages = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(ScreenshotLocationDto other) {
      country(other.getCountry());
      languages(other.getLanguages());
      return this;
    }

    @JsonSetter(
        value = "country",
        nulls = Nulls.SKIP
    )
    public Builder country(Optional<String> country) {
      this.country = country;
      return this;
    }

    public Builder country(String country) {
      this.country = Optional.ofNullable(country);
      return this;
    }

    @JsonSetter(
        value = "languages",
        nulls = Nulls.SKIP
    )
    public Builder languages(Optional<List<String>> languages) {
      this.languages = languages;
      return this;
    }

    public Builder languages(List<String> languages) {
      this.languages = Optional.ofNullable(languages);
      return this;
    }

    public ScreenshotLocationDto build() {
      return new ScreenshotLocationDto(country, languages, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
