/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ScreenshotDtoColorScheme {
  public static final ScreenshotDtoColorScheme LIGHT = new ScreenshotDtoColorScheme(Value.LIGHT, "light");

  public static final ScreenshotDtoColorScheme DARK = new ScreenshotDtoColorScheme(Value.DARK, "dark");

  private final Value value;

  private final String string;

  ScreenshotDtoColorScheme(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ScreenshotDtoColorScheme && this.string.equals(((ScreenshotDtoColorScheme) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case LIGHT:
        return visitor.visitLight();
      case DARK:
        return visitor.visitDark();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ScreenshotDtoColorScheme valueOf(String value) {
    switch (value) {
      case "light":
        return LIGHT;
      case "dark":
        return DARK;
      default:
        return new ScreenshotDtoColorScheme(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    LIGHT,

    DARK,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitLight();

    T visitDark();

    T visitUnknown(String unknownType);
  }
}
