/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ScreenshotClipDto.Builder.class
)
public final class ScreenshotClipDto {
  private final double height;

  private final double width;

  private final double x;

  private final double y;

  private final Map<String, Object> additionalProperties;

  private ScreenshotClipDto(double height, double width, double x, double y,
      Map<String, Object> additionalProperties) {
    this.height = height;
    this.width = width;
    this.x = x;
    this.y = y;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("height")
  public double getHeight() {
    return height;
  }

  @JsonProperty("width")
  public double getWidth() {
    return width;
  }

  @JsonProperty("x")
  public double getX() {
    return x;
  }

  @JsonProperty("y")
  public double getY() {
    return y;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ScreenshotClipDto && equalTo((ScreenshotClipDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ScreenshotClipDto other) {
    return height == other.height && width == other.width && x == other.x && y == other.y;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.height, this.width, this.x, this.y);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static HeightStage builder() {
    return new Builder();
  }

  public interface HeightStage {
    WidthStage height(double height);

    Builder from(ScreenshotClipDto other);
  }

  public interface WidthStage {
    XStage width(double width);
  }

  public interface XStage {
    YStage x(double x);
  }

  public interface YStage {
    _FinalStage y(double y);
  }

  public interface _FinalStage {
    ScreenshotClipDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements HeightStage, WidthStage, XStage, YStage, _FinalStage {
    private double height;

    private double width;

    private double x;

    private double y;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ScreenshotClipDto other) {
      height(other.getHeight());
      width(other.getWidth());
      x(other.getX());
      y(other.getY());
      return this;
    }

    @java.lang.Override
    @JsonSetter("height")
    public WidthStage height(double height) {
      this.height = height;
      return this;
    }

    @java.lang.Override
    @JsonSetter("width")
    public XStage width(double width) {
      this.width = width;
      return this;
    }

    @java.lang.Override
    @JsonSetter("x")
    public YStage x(double x) {
      this.x = x;
      return this;
    }

    @java.lang.Override
    @JsonSetter("y")
    public _FinalStage y(double y) {
      this.y = y;
      return this;
    }

    @java.lang.Override
    public ScreenshotClipDto build() {
      return new ScreenshotClipDto(height, width, x, y, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
