/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchResponse.Builder.class
)
public final class SearchResponse {
  private final int creditsUsed;

  private final List<SearchResult> data;

  private final SearchResponseProvider provider;

  private final String query;

  private final boolean success;

  private final int total;

  private final Map<String, Object> additionalProperties;

  private SearchResponse(int creditsUsed, List<SearchResult> data, SearchResponseProvider provider,
      String query, boolean success, int total, Map<String, Object> additionalProperties) {
    this.creditsUsed = creditsUsed;
    this.data = data;
    this.provider = provider;
    this.query = query;
    this.success = success;
    this.total = total;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("creditsUsed")
  public int getCreditsUsed() {
    return creditsUsed;
  }

  @JsonProperty("data")
  public List<SearchResult> getData() {
    return data;
  }

  @JsonProperty("provider")
  public SearchResponseProvider getProvider() {
    return provider;
  }

  @JsonProperty("query")
  public String getQuery() {
    return query;
  }

  @JsonProperty("success")
  public boolean getSuccess() {
    return success;
  }

  @JsonProperty("total")
  public int getTotal() {
    return total;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchResponse && equalTo((SearchResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchResponse other) {
    return creditsUsed == other.creditsUsed && data.equals(other.data) && provider.equals(other.provider) && query.equals(other.query) && success == other.success && total == other.total;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.creditsUsed, this.data, this.provider, this.query, this.success, this.total);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static CreditsUsedStage builder() {
    return new Builder();
  }

  public interface CreditsUsedStage {
    ProviderStage creditsUsed(int creditsUsed);

    Builder from(SearchResponse other);
  }

  public interface ProviderStage {
    QueryStage provider(@NotNull SearchResponseProvider provider);
  }

  public interface QueryStage {
    SuccessStage query(@NotNull String query);
  }

  public interface SuccessStage {
    TotalStage success(boolean success);
  }

  public interface TotalStage {
    _FinalStage total(int total);
  }

  public interface _FinalStage {
    SearchResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage data(List<SearchResult> data);

    _FinalStage addData(SearchResult data);

    _FinalStage addAllData(List<SearchResult> data);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements CreditsUsedStage, ProviderStage, QueryStage, SuccessStage, TotalStage, _FinalStage {
    private int creditsUsed;

    private SearchResponseProvider provider;

    private String query;

    private boolean success;

    private int total;

    private List<SearchResult> data = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SearchResponse other) {
      creditsUsed(other.getCreditsUsed());
      data(other.getData());
      provider(other.getProvider());
      query(other.getQuery());
      success(other.getSuccess());
      total(other.getTotal());
      return this;
    }

    @java.lang.Override
    @JsonSetter("creditsUsed")
    public ProviderStage creditsUsed(int creditsUsed) {
      this.creditsUsed = creditsUsed;
      return this;
    }

    @java.lang.Override
    @JsonSetter("provider")
    public QueryStage provider(@NotNull SearchResponseProvider provider) {
      this.provider = Objects.requireNonNull(provider, "provider must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("query")
    public SuccessStage query(@NotNull String query) {
      this.query = Objects.requireNonNull(query, "query must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("success")
    public TotalStage success(boolean success) {
      this.success = success;
      return this;
    }

    @java.lang.Override
    @JsonSetter("total")
    public _FinalStage total(int total) {
      this.total = total;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllData(List<SearchResult> data) {
      if (data != null) {
        this.data.addAll(data);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addData(SearchResult data) {
      this.data.add(data);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public _FinalStage data(List<SearchResult> data) {
      this.data.clear();
      if (data != null) {
        this.data.addAll(data);
      }
      return this;
    }

    @java.lang.Override
    public SearchResponse build() {
      return new SearchResponse(creditsUsed, data, provider, query, success, total, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
