/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SummaryFormatDto.Builder.class
)
public final class SummaryFormatDto {
  private final Optional<String> query;

  private final SummaryFormatDtoType type;

  private final Map<String, Object> additionalProperties;

  private SummaryFormatDto(Optional<String> query, SummaryFormatDtoType type,
      Map<String, Object> additionalProperties) {
    this.query = query;
    this.type = type;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Specific query for focused summarization
   */
  @JsonProperty("query")
  public Optional<String> getQuery() {
    return query;
  }

  /**
   * @return Format type
   */
  @JsonProperty("type")
  public SummaryFormatDtoType getType() {
    return type;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SummaryFormatDto && equalTo((SummaryFormatDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SummaryFormatDto other) {
    return query.equals(other.query) && type.equals(other.type);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.query, this.type);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    /**
     * <p>Format type</p>
     */
    _FinalStage type(@NotNull SummaryFormatDtoType type);

    Builder from(SummaryFormatDto other);
  }

  public interface _FinalStage {
    SummaryFormatDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Specific query for focused summarization</p>
     */
    _FinalStage query(Optional<String> query);

    _FinalStage query(String query);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, _FinalStage {
    private SummaryFormatDtoType type;

    private Optional<String> query = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SummaryFormatDto other) {
      query(other.getQuery());
      type(other.getType());
      return this;
    }

    /**
     * <p>Format type</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("type")
    public _FinalStage type(@NotNull SummaryFormatDtoType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    /**
     * <p>Specific query for focused summarization</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage query(String query) {
      this.query = Optional.ofNullable(query);
      return this;
    }

    /**
     * <p>Specific query for focused summarization</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "query",
        nulls = Nulls.SKIP
    )
    public _FinalStage query(Optional<String> query) {
      this.query = query;
      return this;
    }

    @java.lang.Override
    public SummaryFormatDto build() {
      return new SummaryFormatDto(query, type, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
