/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class SummaryFormatDtoType {
  public static final SummaryFormatDtoType SUMMARY = new SummaryFormatDtoType(Value.SUMMARY, "summary");

  private final Value value;

  private final String string;

  SummaryFormatDtoType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof SummaryFormatDtoType && this.string.equals(((SummaryFormatDtoType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SUMMARY:
        return visitor.visitSummary();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static SummaryFormatDtoType valueOf(String value) {
    switch (value) {
      case "summary":
        return SUMMARY;
      default:
        return new SummaryFormatDtoType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    SUMMARY,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitSummary();

    T visitUnknown(String unknownType);
  }
}
