/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TestWebhookResponse.Builder.class
)
public final class TestWebhookResponse {
  private final String event;

  private final String message;

  private final Map<String, Object> payload;

  private final boolean success;

  private final Map<String, Object> additionalProperties;

  private TestWebhookResponse(String event, String message, Map<String, Object> payload,
      boolean success, Map<String, Object> additionalProperties) {
    this.event = event;
    this.message = message;
    this.payload = payload;
    this.success = success;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("event")
  public String getEvent() {
    return event;
  }

  @JsonProperty("message")
  public String getMessage() {
    return message;
  }

  @JsonProperty("payload")
  public Map<String, Object> getPayload() {
    return payload;
  }

  @JsonProperty("success")
  public boolean getSuccess() {
    return success;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TestWebhookResponse && equalTo((TestWebhookResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TestWebhookResponse other) {
    return event.equals(other.event) && message.equals(other.message) && payload.equals(other.payload) && success == other.success;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.event, this.message, this.payload, this.success);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static EventStage builder() {
    return new Builder();
  }

  public interface EventStage {
    MessageStage event(@NotNull String event);

    Builder from(TestWebhookResponse other);
  }

  public interface MessageStage {
    SuccessStage message(@NotNull String message);
  }

  public interface SuccessStage {
    _FinalStage success(boolean success);
  }

  public interface _FinalStage {
    TestWebhookResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage payload(Map<String, Object> payload);

    _FinalStage putAllPayload(Map<String, Object> payload);

    _FinalStage payload(String key, Object value);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements EventStage, MessageStage, SuccessStage, _FinalStage {
    private String event;

    private String message;

    private boolean success;

    private Map<String, Object> payload = new LinkedHashMap<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TestWebhookResponse other) {
      event(other.getEvent());
      message(other.getMessage());
      payload(other.getPayload());
      success(other.getSuccess());
      return this;
    }

    @java.lang.Override
    @JsonSetter("event")
    public MessageStage event(@NotNull String event) {
      this.event = Objects.requireNonNull(event, "event must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("message")
    public SuccessStage message(@NotNull String message) {
      this.message = Objects.requireNonNull(message, "message must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("success")
    public _FinalStage success(boolean success) {
      this.success = success;
      return this;
    }

    @java.lang.Override
    public _FinalStage payload(String key, Object value) {
      this.payload.put(key, value);
      return this;
    }

    @java.lang.Override
    public _FinalStage putAllPayload(Map<String, Object> payload) {
      if (payload != null) {
        this.payload.putAll(payload);
      }
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "payload",
        nulls = Nulls.SKIP
    )
    public _FinalStage payload(Map<String, Object> payload) {
      this.payload.clear();
      if (payload != null) {
        this.payload.putAll(payload);
      }
      return this;
    }

    @java.lang.Override
    public TestWebhookResponse build() {
      return new TestWebhookResponse(event, message, payload, success, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
