/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Webhook.Builder.class
)
public final class Webhook {
  private final Optional<OffsetDateTime> createdAt;

  private final List<String> events;

  private final String id;

  private final boolean isActive;

  private final Optional<List<Map<String, Object>>> recentDeliveries;

  private final Optional<String> secret;

  private final Optional<OffsetDateTime> updatedAt;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private Webhook(Optional<OffsetDateTime> createdAt, List<String> events, String id,
      boolean isActive, Optional<List<Map<String, Object>>> recentDeliveries,
      Optional<String> secret, Optional<OffsetDateTime> updatedAt, String url,
      Map<String, Object> additionalProperties) {
    this.createdAt = createdAt;
    this.events = events;
    this.id = id;
    this.isActive = isActive;
    this.recentDeliveries = recentDeliveries;
    this.secret = secret;
    this.updatedAt = updatedAt;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("createdAt")
  public Optional<OffsetDateTime> getCreatedAt() {
    return createdAt;
  }

  @JsonProperty("events")
  public List<String> getEvents() {
    return events;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("isActive")
  public boolean getIsActive() {
    return isActive;
  }

  @JsonProperty("recentDeliveries")
  public Optional<List<Map<String, Object>>> getRecentDeliveries() {
    return recentDeliveries;
  }

  @JsonProperty("secret")
  public Optional<String> getSecret() {
    return secret;
  }

  @JsonProperty("updatedAt")
  public Optional<OffsetDateTime> getUpdatedAt() {
    return updatedAt;
  }

  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Webhook && equalTo((Webhook) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Webhook other) {
    return createdAt.equals(other.createdAt) && events.equals(other.events) && id.equals(other.id) && isActive == other.isActive && recentDeliveries.equals(other.recentDeliveries) && secret.equals(other.secret) && updatedAt.equals(other.updatedAt) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.createdAt, this.events, this.id, this.isActive, this.recentDeliveries, this.secret, this.updatedAt, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    IsActiveStage id(@NotNull String id);

    Builder from(Webhook other);
  }

  public interface IsActiveStage {
    UrlStage isActive(boolean isActive);
  }

  public interface UrlStage {
    _FinalStage url(@NotNull String url);
  }

  public interface _FinalStage {
    Webhook build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage createdAt(Optional<OffsetDateTime> createdAt);

    _FinalStage createdAt(OffsetDateTime createdAt);

    _FinalStage events(List<String> events);

    _FinalStage addEvents(String events);

    _FinalStage addAllEvents(List<String> events);

    _FinalStage recentDeliveries(Optional<List<Map<String, Object>>> recentDeliveries);

    _FinalStage recentDeliveries(List<Map<String, Object>> recentDeliveries);

    _FinalStage secret(Optional<String> secret);

    _FinalStage secret(String secret);

    _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt);

    _FinalStage updatedAt(OffsetDateTime updatedAt);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, IsActiveStage, UrlStage, _FinalStage {
    private String id;

    private boolean isActive;

    private String url;

    private Optional<OffsetDateTime> updatedAt = Optional.empty();

    private Optional<String> secret = Optional.empty();

    private Optional<List<Map<String, Object>>> recentDeliveries = Optional.empty();

    private List<String> events = new ArrayList<>();

    private Optional<OffsetDateTime> createdAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Webhook other) {
      createdAt(other.getCreatedAt());
      events(other.getEvents());
      id(other.getId());
      isActive(other.getIsActive());
      recentDeliveries(other.getRecentDeliveries());
      secret(other.getSecret());
      updatedAt(other.getUpdatedAt());
      url(other.getUrl());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public IsActiveStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("isActive")
    public UrlStage isActive(boolean isActive) {
      this.isActive = isActive;
      return this;
    }

    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage updatedAt(OffsetDateTime updatedAt) {
      this.updatedAt = Optional.ofNullable(updatedAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "updatedAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt) {
      this.updatedAt = updatedAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage secret(String secret) {
      this.secret = Optional.ofNullable(secret);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "secret",
        nulls = Nulls.SKIP
    )
    public _FinalStage secret(Optional<String> secret) {
      this.secret = secret;
      return this;
    }

    @java.lang.Override
    public _FinalStage recentDeliveries(List<Map<String, Object>> recentDeliveries) {
      this.recentDeliveries = Optional.ofNullable(recentDeliveries);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "recentDeliveries",
        nulls = Nulls.SKIP
    )
    public _FinalStage recentDeliveries(Optional<List<Map<String, Object>>> recentDeliveries) {
      this.recentDeliveries = recentDeliveries;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllEvents(List<String> events) {
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addEvents(String events) {
      this.events.add(events);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "events",
        nulls = Nulls.SKIP
    )
    public _FinalStage events(List<String> events) {
      this.events.clear();
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage createdAt(OffsetDateTime createdAt) {
      this.createdAt = Optional.ofNullable(createdAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "createdAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage createdAt(Optional<OffsetDateTime> createdAt) {
      this.createdAt = createdAt;
      return this;
    }

    @java.lang.Override
    public Webhook build() {
      return new Webhook(createdAt, events, id, isActive, recentDeliveries, secret, updatedAt, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
