/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.types;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = WebhookConfigDto.Builder.class
)
public final class WebhookConfigDto {
  private final List<String> events;

  private final Optional<Map<String, Object>> metadata;

  private final Optional<String> secret;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private WebhookConfigDto(List<String> events, Optional<Map<String, Object>> metadata,
      Optional<String> secret, String url, Map<String, Object> additionalProperties) {
    this.events = events;
    this.metadata = metadata;
    this.secret = secret;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Events to subscribe to
   */
  @JsonProperty("events")
  public List<String> getEvents() {
    return events;
  }

  /**
   * @return Additional metadata
   */
  @JsonProperty("metadata")
  public Optional<Map<String, Object>> getMetadata() {
    return metadata;
  }

  /**
   * @return Optional secret used to sign direct webhook deliveries
   */
  @JsonProperty("secret")
  public Optional<String> getSecret() {
    return secret;
  }

  /**
   * @return Webhook URL
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof WebhookConfigDto && equalTo((WebhookConfigDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(WebhookConfigDto other) {
    return events.equals(other.events) && metadata.equals(other.metadata) && secret.equals(other.secret) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.events, this.metadata, this.secret, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    /**
     * <p>Webhook URL</p>
     */
    _FinalStage url(@NotNull String url);

    Builder from(WebhookConfigDto other);
  }

  public interface _FinalStage {
    WebhookConfigDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Events to subscribe to</p>
     */
    _FinalStage events(List<String> events);

    _FinalStage addEvents(String events);

    _FinalStage addAllEvents(List<String> events);

    /**
     * <p>Additional metadata</p>
     */
    _FinalStage metadata(Optional<Map<String, Object>> metadata);

    _FinalStage metadata(Map<String, Object> metadata);

    /**
     * <p>Optional secret used to sign direct webhook deliveries</p>
     */
    _FinalStage secret(Optional<String> secret);

    _FinalStage secret(String secret);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, _FinalStage {
    private String url;

    private Optional<String> secret = Optional.empty();

    private Optional<Map<String, Object>> metadata = Optional.empty();

    private List<String> events = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(WebhookConfigDto other) {
      events(other.getEvents());
      metadata(other.getMetadata());
      secret(other.getSecret());
      url(other.getUrl());
      return this;
    }

    /**
     * <p>Webhook URL</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>Optional secret used to sign direct webhook deliveries</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage secret(String secret) {
      this.secret = Optional.ofNullable(secret);
      return this;
    }

    /**
     * <p>Optional secret used to sign direct webhook deliveries</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "secret",
        nulls = Nulls.SKIP
    )
    public _FinalStage secret(Optional<String> secret) {
      this.secret = secret;
      return this;
    }

    /**
     * <p>Additional metadata</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage metadata(Map<String, Object> metadata) {
      this.metadata = Optional.ofNullable(metadata);
      return this;
    }

    /**
     * <p>Additional metadata</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "metadata",
        nulls = Nulls.SKIP
    )
    public _FinalStage metadata(Optional<Map<String, Object>> metadata) {
      this.metadata = metadata;
      return this;
    }

    /**
     * <p>Events to subscribe to</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllEvents(List<String> events) {
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    /**
     * <p>Events to subscribe to</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addEvents(String events) {
      this.events.add(events);
      return this;
    }

    /**
     * <p>Events to subscribe to</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "events",
        nulls = Nulls.SKIP
    )
    public _FinalStage events(List<String> events) {
      this.events.clear();
      if (events != null) {
        this.events.addAll(events);
      }
      return this;
    }

    @java.lang.Override
    public WebhookConfigDto build() {
      return new WebhookConfigDto(events, metadata, secret, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
