/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.brand.requests;

import com.berrycrawl.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BrandDto.Builder.class
)
public final class BrandDto {
  private final Optional<Boolean> refresh;

  private final Optional<Double> timeout;

  private final String url;

  private final Map<String, Object> additionalProperties;

  private BrandDto(Optional<Boolean> refresh, Optional<Double> timeout, String url,
      Map<String, Object> additionalProperties) {
    this.refresh = refresh;
    this.timeout = timeout;
    this.url = url;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Ignore a cached profile and fetch the website again
   */
  @JsonProperty("refresh")
  public Optional<Boolean> getRefresh() {
    return refresh;
  }

  /**
   * @return Maximum time to spend building the profile, in milliseconds
   */
  @JsonProperty("timeout")
  public Optional<Double> getTimeout() {
    return timeout;
  }

  /**
   * @return The public website whose brand profile should be extracted
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BrandDto && equalTo((BrandDto) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BrandDto other) {
    return refresh.equals(other.refresh) && timeout.equals(other.timeout) && url.equals(other.url);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.refresh, this.timeout, this.url);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static UrlStage builder() {
    return new Builder();
  }

  public interface UrlStage {
    /**
     * <p>The public website whose brand profile should be extracted</p>
     */
    _FinalStage url(@NotNull String url);

    Builder from(BrandDto other);
  }

  public interface _FinalStage {
    BrandDto build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Ignore a cached profile and fetch the website again</p>
     */
    _FinalStage refresh(Optional<Boolean> refresh);

    _FinalStage refresh(Boolean refresh);

    /**
     * <p>Maximum time to spend building the profile, in milliseconds</p>
     */
    _FinalStage timeout(Optional<Double> timeout);

    _FinalStage timeout(Double timeout);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements UrlStage, _FinalStage {
    private String url;

    private Optional<Double> timeout = Optional.empty();

    private Optional<Boolean> refresh = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BrandDto other) {
      refresh(other.getRefresh());
      timeout(other.getTimeout());
      url(other.getUrl());
      return this;
    }

    /**
     * <p>The public website whose brand profile should be extracted</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public _FinalStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>Maximum time to spend building the profile, in milliseconds</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage timeout(Double timeout) {
      this.timeout = Optional.ofNullable(timeout);
      return this;
    }

    /**
     * <p>Maximum time to spend building the profile, in milliseconds</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "timeout",
        nulls = Nulls.SKIP
    )
    public _FinalStage timeout(Optional<Double> timeout) {
      this.timeout = timeout;
      return this;
    }

    /**
     * <p>Ignore a cached profile and fetch the website again</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage refresh(Boolean refresh) {
      this.refresh = Optional.ofNullable(refresh);
      return this;
    }

    /**
     * <p>Ignore a cached profile and fetch the website again</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "refresh",
        nulls = Nulls.SKIP
    )
    public _FinalStage refresh(Optional<Boolean> refresh) {
      this.refresh = refresh;
      return this;
    }

    @java.lang.Override
    public BrandDto build() {
      return new BrandDto(refresh, timeout, url, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
