/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.brand;

import com.berrycrawl.core.ClientOptions;
import com.berrycrawl.core.RequestOptions;
import com.berrycrawl.resources.brand.requests.BrandDto;
import com.berrycrawl.types.BrandResponse;

public class BrandClient {
  protected final ClientOptions clientOptions;

  private final RawBrandClient rawClient;

  public BrandClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawBrandClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawBrandClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Send one website URL. BerryCrawl returns the brand identity found on that site.
   */
  public BrandResponse retrieve(BrandDto request) {
    return this.rawClient.retrieve(request).body();
  }

  /**
   * Send one website URL. BerryCrawl returns the brand identity found on that site.
   */
  public BrandResponse retrieve(BrandDto request, RequestOptions requestOptions) {
    return this.rawClient.retrieve(request, requestOptions).body();
  }
}
