/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListJobsRequestStatus {
  public static final ListJobsRequestStatus CANCELLED = new ListJobsRequestStatus(Value.CANCELLED, "CANCELLED");

  public static final ListJobsRequestStatus RUNNING = new ListJobsRequestStatus(Value.RUNNING, "RUNNING");

  public static final ListJobsRequestStatus PENDING = new ListJobsRequestStatus(Value.PENDING, "PENDING");

  public static final ListJobsRequestStatus FAILED = new ListJobsRequestStatus(Value.FAILED, "FAILED");

  public static final ListJobsRequestStatus COMPLETED = new ListJobsRequestStatus(Value.COMPLETED, "COMPLETED");

  private final Value value;

  private final String string;

  ListJobsRequestStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListJobsRequestStatus && this.string.equals(((ListJobsRequestStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case CANCELLED:
        return visitor.visitCancelled();
      case RUNNING:
        return visitor.visitRunning();
      case PENDING:
        return visitor.visitPending();
      case FAILED:
        return visitor.visitFailed();
      case COMPLETED:
        return visitor.visitCompleted();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListJobsRequestStatus valueOf(String value) {
    switch (value) {
      case "CANCELLED":
        return CANCELLED;
      case "RUNNING":
        return RUNNING;
      case "PENDING":
        return PENDING;
      case "FAILED":
        return FAILED;
      case "COMPLETED":
        return COMPLETED;
      default:
        return new ListJobsRequestStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PENDING,

    RUNNING,

    COMPLETED,

    FAILED,

    CANCELLED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPending();

    T visitRunning();

    T visitCompleted();

    T visitFailed();

    T visitCancelled();

    T visitUnknown(String unknownType);
  }
}
