/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.berrycrawl.resources.jobs.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class ListJobsRequestType {
  public static final ListJobsRequestType EXTRACT = new ListJobsRequestType(Value.EXTRACT, "extract");

  public static final ListJobsRequestType CRAWL = new ListJobsRequestType(Value.CRAWL, "crawl");

  private final Value value;

  private final String string;

  ListJobsRequestType(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof ListJobsRequestType && this.string.equals(((ListJobsRequestType) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case EXTRACT:
        return visitor.visitExtract();
      case CRAWL:
        return visitor.visitCrawl();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static ListJobsRequestType valueOf(String value) {
    switch (value) {
      case "extract":
        return EXTRACT;
      case "crawl":
        return CRAWL;
      default:
        return new ListJobsRequestType(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    CRAWL,

    EXTRACT,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitCrawl();

    T visitExtract();

    T visitUnknown(String unknownType);
  }
}
